In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pyreadstat
import re

In [2]:
pd.options.display.max_columns = 100

In [3]:
df_1 = pd.read_csv("../data/Datafiniti_Vegetarian_and_Vegan_Restaurants.csv")

In [4]:
df_1.head(n=10)

,id,dateAdded,dateUpdated,address,categories,primaryCategories,city,claimed,country,cuisines,descriptions.dateSeen,descriptions.sourceURLs,descriptions.value,facebookPageURL,features.key,features.value,hours.day,hours.dept,hours.hour,imageURLs,isClosed,keys,languagesSpoken,latitude,longitude,menuPageURL,menus.amountMax,menus.amountMin,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,menus.sourceURLs,name,paymentTypes,phones,postalCode,priceRangeCurrency,priceRangeMin,priceRangeMax,province,sic,sourceURLs,twitter,websites,yearOpened
0,AVwd3yXEkufWRAb59-sH,2016-04-22T02:47:48Z,2018-09-10T21:00:49Z,1045 San Pablo Ave,"Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...",Accommodation & Food Services,Albany,NaN,US,"Thai,Asian/Pacific,Vegetarian",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://igx.4sqi.net/img/general/600x600/o_h1i...,NaN,us/ca/albany/1045sanpabloave/-1106202297,NaN,37.885131,-122.297013,http://www.singlepage.com/ruen-pair-authentic-...,13.95,3.75,NaN,USD,2016-04-22T02:48:00.000Z,"Squash, carrots, butternut squash and potato",Baked Kabocha,https://foursquare.com/v/potala-organic-cafe/4...,Potala Organic Cafe,NaN,(510) 528-2375,94706,NaN,NaN,NaN,CA,NaN,https://foursquare.com/v/potala-organic-cafe/4...,NaN,"http://www.potala.us/,http://potala.us",NaN
1,AVwd3yXEkufWRAb59-sH,2016-04-22T02:47:48Z,2018-09-10T21:00:49Z,1045 San Pablo Ave,"Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...",Accommodation & Food Services,Albany,NaN,US,"Thai,Asian/Pacific,Vegetarian",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://igx.4sqi.net/img/general/600x600/o_h1i...,NaN,us/ca/albany/1045sanpabloave/-1106202297,NaN,37.885131,-122.297013,http://www.singlepage.com/ruen-pair-authentic-...,13.95,3.75,NaN,USD,2016-04-22T02:48:00.000Z,With wild blend brown rice,Short Grain Brown Rice,https://foursquare.com/v/potala-organic-cafe/4...,Potala Organic Cafe,NaN,(510) 528-2375,94706,NaN,NaN,NaN,CA,NaN,https://foursquare.com/v/potala-organic-cafe/4...,NaN,"http://www.potala.us/,http://potala.us",NaN
2,AVwd3yXEkufWRAb59-sH,2016-04-22T02:47:48Z,2018-09-10T21:00:49Z,1045 San Pablo Ave,"Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...",Accommodation & Food Services,Albany,NaN,US,"Thai,Asian/Pacific,Vegetarian",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://igx.4sqi.net/img/general/600x600/o_h1i...,NaN,us/ca/albany/1045sanpabloave/-1106202297,NaN,37.885131,-122.297013,http://www.singlepage.com/ruen-pair-authentic-...,13.95,3.75,NaN,USD,2016-04-22T02:48:00.000Z,NaN,Green Bean Veggie Soup,https://foursquare.com/v/potala-organic-cafe/4...,Potala Organic Cafe,NaN,(510) 528-2375,94706,NaN,NaN,NaN,CA,NaN,https://foursquare.com/v/potala-organic-cafe/4...,NaN,"http://www.potala.us/,http://potala.us",NaN
3,AVwd3yXEkufWRAb59-sH,2016-04-22T02:47:48Z,2018-09-10T21:00:49Z,1045 San Pablo Ave,"Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...",Accommodation & Food Services,Albany,NaN,US,"Thai,Asian/Pacific,Vegetarian",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://igx.4sqi.net/img/general/600x600/o_h1i...,NaN,us/ca/albany/1045sanpabloave/-1106202297,NaN,37.885131,-122.297013,http://www.singlepage.com/ruen-pair-authentic-...,8.95,8.95,NaN,USD,2016-04-22T02:48:00.000Z,NaN,"Steamed Broccoli, Carrots and Turnips",https://foursquare.com/v/potala-organic-cafe/4...,Potala Organic Cafe,NaN,(510) 528-2375,94706,NaN,NaN,NaN,CA,NaN,https://foursquare.com/v/potala-organic-cafe/4...,NaN,"http://www.potala.us/,http://potala.us",NaN
4,AVwd3yXEkufWRAb59-sH,2016-04-22T02:47:48Z,2018-09-10T21:00:49Z,1045 San Pablo Ave,"Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...",Accommodation & Food Services,Albany,NaN,US,"Thai,Asian/Pacific,Vegetarian",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://igx.4sqi.net/img/general/600x600/o_h1i...,NaN,us/ca/albany/1045sanpabloave/-1106202297,NaN,37.885131,-122.297013,http://www.singlepage.com/ruen-pair-authentic-...,13.95,3.75,NaN,USD,2016-04-22T02:48:00.000Z,With vinegar tahini beet dressing,Mixed Green Salad,https://foursquare.com/v/potala-organic-cafe/4...,Potala Organic Cafe,NaN,(510) 528-2375,94706,NaN,NaN,NaN,CA,NaN,https://foursquare.com/v/potala-organic-cafe/4...,NaN,"http://www.potala.us/,http://potala.us",NaN
5,AVwddQkGkufWRAb56GvX,2016-03-24T10:25:20Z,2018-09-04T13:02:10Z,16411 Bernardo Center Dr,"Indian Restaurant,Restaurant,Caterers,Food Din...",Accommodation & Food Services,San Diego,NaN,US,"Vegetarian,Indian",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://irs3.4sqi.net/img/general/200x200/2099...,NaN,us/ca/sandiego/16411bernardocenterdr/1998744718,NaN,33.012662,-117.078590,http://www.citysearch.com/profile/menu/490729?...,2.49,2.49,Side Orders,USD,"2018-04-08T08:28:33.338Z,2018-07-01T12:12:35.4...",NaN,Mixed Pickles,https://www.allmenus.com/ca/san-diego/29208-pa...,Passage To India,"American Express,VISA",(858) 674-7500,92128,USD,25.0,40.0,CA,NaN,http://www.superpages.com/bp/san-diego-ca/pass...,NaN,http://passagetoindiasd.com,NaN
6,AVwddQkGkufWRAb56GvX,2016-03-24T10:25:20Z,2018-09-04T13:02:10Z,16411 Bernardo Center Dr,"Indian Restaurant,Restaurant,Caterers,Food Din...",Accommodation & Food Services,San Diego,NaN,US,"Vegetarian,Indian",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://irs3.4sqi.net/img/general/200x200/2099...,NaN,us/ca/sandiego/16411bernardocenterdr/1998744718,NaN,33.012662,-117.078590,http://www.citysearch.com/profile/menu/490729?...,6.99,6.99,Appetizers,USD,"2018-04-08T08:28:33.338Z,2018-07-01T12:12:35.4...",NaN,Cheese Pakora,https://www.allmenus.com/ca/san-diego/29208-pa...,Passage To India,"American Express,VISA",(858) 674-7500,92128,USD,25.0,40.0,CA,NaN,http://www.superpages.com/bp/san-diego-ca/pass...,NaN,http://passagetoindiasd.com,NaN
7,AVwddQkGkufWRAb56GvX,2016-03-24T10:25:20Z,2018-09-04T13:02:10Z,16411 Bernardo Center Dr,"Indian Restaurant,Restaurant,Caterers,Food Din...",Accommodation & Food Services,San Diego,NaN,US,"Vegetarian,Indian",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://irs3.4sqi.net/img/general/200x200/2099...,NaN,us/ca/sandiego/16411bernardocenterdr/1998744718,NaN,33.012662,-117.078590,http://www.citysearch.com/profile/menu/490729?...,2.99,2.99,Side Orders,USD,"2018-04-08T08:28:33.338Z,2018-07-01T12:12:35.4...",NaN,Mango Chutney,https://www.allmenus.com/ca/san-diego/29208-pa...,Passage To India,"American Express,VISA",(858) 674-7500,92128,USD,25.0,40.0,CA,NaN,http://www.superpages.com/bp/san-diego-ca/pass...,NaN,http://passagetoindiasd.com,NaN
8,AVwddQkGkufWRAb56GvX,2016-03-24T10:25:20Z,2018-09-04T13:02:10Z,16411 Bernardo Center Dr,"Indian Restaurant,Restaurant,Caterers,Food Din...",Accommodation & Food Services,San Diego,NaN,US,"Vegetarian,Indian",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://irs3.4sqi.net/img/general/200x200/2099...,NaN,us/ca/sandiego/16411bernardocenterdr/1998744718,NaN,33.012662,-117.078590,http://www.citysearch.com/profile/menu/490729?...,1.99,1.99,Traditional Tandoori Breads,USD,"2018-07-01T12:12:35.481Z,2018-04-08T08:28:33.3...",NaN,Tanoodri Roti,https://www.allmenus.com/ca/san-diego/29208-pa...,Passage To India,"American Express,VISA",(858) 674-7500,92128,USD,25.0,40.0,CA,NaN,http://www.superpages.com/bp/san-diego-ca/pass...,NaN,http://passagetoindiasd.com,NaN
9,AVwddQkGkufWRAb56GvX,2016-03-24T10:25:20Z,2018-09-04T13:02:10Z,16411 Bernardo Center Dr,"Indian Restaurant,Restaurant,Caterers,Food Din...",Accommodation & Food Services,San Diego,NaN,US,"Vegetarian,Indian",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://irs3.4sqi.net/img/general/200x200/2099...,NaN,us/ca/sandiego/16411bernardocenterdr/1998744718,NaN,33.012662,-117.078590,http://www.citysearch.com/profile/menu/490729?...,12.99,12.99,Tandoori Sizzlers,USD,"2018-04-08T08:28:33.338Z,2018-07-01T12:12:35.4...",NaN,Seekh Kebab,https://www.allmenus.com/ca/san-diego/29208-pa...,Passage To India,"American Express,VISA",(858) 674-7500,92128,USD,25.0,40.0,CA,NaN,http://www.superpages.com/bp/san-diego-ca/pass...,NaN,http://passagetoindiasd.com,NaN

In [5]:
df_1.columns

Index(['id', 'dateAdded', 'dateUpdated', 'address', 'categories',
       'primaryCategories', 'city', 'claimed', 'country', 'cuisines',
       'descriptions.dateSeen', 'descriptions.sourceURLs',
       'descriptions.value', 'facebookPageURL', 'features.key',
       'features.value', 'hours.day', 'hours.dept', 'hours.hour', 'imageURLs',
       'isClosed', 'keys', 'languagesSpoken', 'latitude', 'longitude',
       'menuPageURL', 'menus.amountMax', 'menus.amountMin', 'menus.category',
       'menus.currency', 'menus.dateSeen', 'menus.description', 'menus.name',
       'menus.sourceURLs', 'name', 'paymentTypes', 'phones', 'postalCode',
       'priceRangeCurrency', 'priceRangeMin', 'priceRangeMax', 'province',
       'sic', 'sourceURLs', 'twitter', 'websites', 'yearOpened'],
      dtype='object')

In [6]:
df_1['claimed'].isna().any()

True

In [7]:
df_1.shape

(10000, 47)

In [8]:
df_1['country'].isna().any()

False

In [9]:
df_1['cuisines'].isna().any()

False

In [10]:
df_1['descriptions.dateSeen'].isna().any()

True

In [11]:
df_1['descriptions.dateSeen'].value_counts()

Series([], Name: descriptions.dateSeen, dtype: int64)

In [12]:
df_1['isClosed'].value_counts()

False    20
True     17
Name: isClosed, dtype: int64

In [13]:
df_1['isClosed'].isna().any()

True

In [14]:
df_1['languagesSpoken'].isna().any()

True

In [15]:
df_1['languagesSpoken'].value_counts()

Series([], Name: languagesSpoken, dtype: int64)

In [16]:
df_1['menus.category'].value_counts()

Beverages                   287
Appetizers                  262
Sides                       196
Desserts                    153
Salads                      127
                           ...
Pao                           1
House Specialties             1
Kids 8 ampamp Younger         1
Step 1 Choose Your Style      1
Salads 1095                   1
Name: menus.category, Length: 818, dtype: int64

In [17]:
df_1['menus.category'].isna().any()

True

In [18]:
df_1['paymentTypes'].isna().any()

True

In [19]:
df_1['paymentTypes'].value_counts()

AMEX                                                                        367
American Express,Discover,Mastercard,Visa                                   267
American Express,Mastercard,Visa                                            225
Mastercard,Visa                                                             219
American Express,Debit Card,Discover,Mastercard                             217
Cash                                                                        216
amex                                                                        189
Visa,MasterCard                                                             179
Mastercard,Discover,Visa,American Express,Diners Club,diners club           168
Mastercard,Visa,American Express,Diners Club                                146
Mastercard,Discover,Visa,American Express                                   142
American Express,MasterCard                                                 135
mastercard                                                                  129
Mastercard,Visa,American Express                                            129
MasterCard                                                                   99
Cash,Mastercard,Visa                                                         97
Discover,Visa                                                                91
American Express,Mastercard,Visa,discover                                    73
American Express                                                             68
American Express,Mastercard,Visa,Discover                                    65
AMEX,American Express                                                        60
master card,amex,visa                                                        56
amex,discover,master card,visa,Mastercard,Discover,Visa,American Express     50
American Express,Visa,Discover,Cash,Mastercard                               50
discover,mastercard,amex                                                     42
amex,visa                                                                    39
American Express,Cash,Debit Card,Mastercard,Visa                             35
American Express,VISA                                                        32
discover,amex                                                                32
Mastercard,Discover,Visa,American Express,Check                              31
amex,discover,mastercard,visa                                                31
Mastercard,Discover,Visa,American Express,Diners Club                        29
Visa,American Express                                                        26
visa                                                                         24
Mastercard                                                                   23
Cash,Check,Discover,Mastercard,Visa                                          18
discover,visa,amex,mastercard,MasterCard                                     17
American Express,Discover,Mastercard,Visa,amex,visa,discover,master card     17
American Express,Diners Club,Mastercard,Visa                                 16
amex,mastercard,discover,visa,AMEX                                           13
American Express,Diners Club,Discover,Mastercard,Visa                        10
Mastercard,Discover,Visa,Travelers Check,American Express                     1
Name: paymentTypes, dtype: int64

In [20]:
df_1['priceRangeCurrency'].value_counts()

USD    6327
Name: priceRangeCurrency, dtype: int64

In [21]:
df_1['sic'].value_counts()

5610.0    104
8129.0     20
4773.0     16
Name: sic, dtype: int64

In [22]:
df_1['yearOpened'].value_counts()

2015.0    91
Name: yearOpened, dtype: int64

In [23]:
df_1['categories']

0       Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...
1       Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...
2       Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...
3       Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...
4       Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...
                              ...
9995    Vegetarian / Vegan Restaurant,Restaurant,Medit...
9996    Vegetarian / Vegan Restaurant,Restaurant,Medit...
9997    Vegetarian / Vegan Restaurant,Restaurant,Medit...
9998    Vegetarian / Vegan Restaurant,Restaurant,Medit...
9999    Vegetarian / Vegan Restaurant,Restaurant,Medit...
Name: categories, Length: 10000, dtype: object

In [24]:
df_1.shape

(10000, 47)

In [25]:
df_1.columns

Index(['id', 'dateAdded', 'dateUpdated', 'address', 'categories',
       'primaryCategories', 'city', 'claimed', 'country', 'cuisines',
       'descriptions.dateSeen', 'descriptions.sourceURLs',
       'descriptions.value', 'facebookPageURL', 'features.key',
       'features.value', 'hours.day', 'hours.dept', 'hours.hour', 'imageURLs',
       'isClosed', 'keys', 'languagesSpoken', 'latitude', 'longitude',
       'menuPageURL', 'menus.amountMax', 'menus.amountMin', 'menus.category',
       'menus.currency', 'menus.dateSeen', 'menus.description', 'menus.name',
       'menus.sourceURLs', 'name', 'paymentTypes', 'phones', 'postalCode',
       'priceRangeCurrency', 'priceRangeMin', 'priceRangeMax', 'province',
       'sic', 'sourceURLs', 'twitter', 'websites', 'yearOpened'],
      dtype='object')

#### For few columns everything is filled with NA. We will be removing those columns from our analysis

In [26]:
df_1.drop(columns=["descriptions.dateSeen","descriptions.sourceURLs","descriptions.value","features.key",
                  "features.value","hours.day","hours.dept","hours.hour","languagesSpoken","isClosed",
                   "yearOpened","sic","claimed","facebookPageURL","twitter"],inplace=True)

In [27]:
df_1.columns

Index(['id', 'dateAdded', 'dateUpdated', 'address', 'categories',
       'primaryCategories', 'city', 'country', 'cuisines', 'imageURLs', 'keys',
       'latitude', 'longitude', 'menuPageURL', 'menus.amountMax',
       'menus.amountMin', 'menus.category', 'menus.currency', 'menus.dateSeen',
       'menus.description', 'menus.name', 'menus.sourceURLs', 'name',
       'paymentTypes', 'phones', 'postalCode', 'priceRangeCurrency',
       'priceRangeMin', 'priceRangeMax', 'province', 'sourceURLs', 'websites'],
      dtype='object')

In [28]:
df_1.head(n=10)

,id,dateAdded,dateUpdated,address,categories,primaryCategories,city,country,cuisines,imageURLs,keys,latitude,longitude,menuPageURL,menus.amountMax,menus.amountMin,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,menus.sourceURLs,name,paymentTypes,phones,postalCode,priceRangeCurrency,priceRangeMin,priceRangeMax,province,sourceURLs,websites
0,AVwd3yXEkufWRAb59-sH,2016-04-22T02:47:48Z,2018-09-10T21:00:49Z,1045 San Pablo Ave,"Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...",Accommodation & Food Services,Albany,US,"Thai,Asian/Pacific,Vegetarian",https://igx.4sqi.net/img/general/600x600/o_h1i...,us/ca/albany/1045sanpabloave/-1106202297,37.885131,-122.297013,http://www.singlepage.com/ruen-pair-authentic-...,13.95,3.75,NaN,USD,2016-04-22T02:48:00.000Z,"Squash, carrots, butternut squash and potato",Baked Kabocha,https://foursquare.com/v/potala-organic-cafe/4...,Potala Organic Cafe,NaN,(510) 528-2375,94706,NaN,NaN,NaN,CA,https://foursquare.com/v/potala-organic-cafe/4...,"http://www.potala.us/,http://potala.us"
1,AVwd3yXEkufWRAb59-sH,2016-04-22T02:47:48Z,2018-09-10T21:00:49Z,1045 San Pablo Ave,"Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...",Accommodation & Food Services,Albany,US,"Thai,Asian/Pacific,Vegetarian",https://igx.4sqi.net/img/general/600x600/o_h1i...,us/ca/albany/1045sanpabloave/-1106202297,37.885131,-122.297013,http://www.singlepage.com/ruen-pair-authentic-...,13.95,3.75,NaN,USD,2016-04-22T02:48:00.000Z,With wild blend brown rice,Short Grain Brown Rice,https://foursquare.com/v/potala-organic-cafe/4...,Potala Organic Cafe,NaN,(510) 528-2375,94706,NaN,NaN,NaN,CA,https://foursquare.com/v/potala-organic-cafe/4...,"http://www.potala.us/,http://potala.us"
2,AVwd3yXEkufWRAb59-sH,2016-04-22T02:47:48Z,2018-09-10T21:00:49Z,1045 San Pablo Ave,"Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...",Accommodation & Food Services,Albany,US,"Thai,Asian/Pacific,Vegetarian",https://igx.4sqi.net/img/general/600x600/o_h1i...,us/ca/albany/1045sanpabloave/-1106202297,37.885131,-122.297013,http://www.singlepage.com/ruen-pair-authentic-...,13.95,3.75,NaN,USD,2016-04-22T02:48:00.000Z,NaN,Green Bean Veggie Soup,https://foursquare.com/v/potala-organic-cafe/4...,Potala Organic Cafe,NaN,(510) 528-2375,94706,NaN,NaN,NaN,CA,https://foursquare.com/v/potala-organic-cafe/4...,"http://www.potala.us/,http://potala.us"
3,AVwd3yXEkufWRAb59-sH,2016-04-22T02:47:48Z,2018-09-10T21:00:49Z,1045 San Pablo Ave,"Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...",Accommodation & Food Services,Albany,US,"Thai,Asian/Pacific,Vegetarian",https://igx.4sqi.net/img/general/600x600/o_h1i...,us/ca/albany/1045sanpabloave/-1106202297,37.885131,-122.297013,http://www.singlepage.com/ruen-pair-authentic-...,8.95,8.95,NaN,USD,2016-04-22T02:48:00.000Z,NaN,"Steamed Broccoli, Carrots and Turnips",https://foursquare.com/v/potala-organic-cafe/4...,Potala Organic Cafe,NaN,(510) 528-2375,94706,NaN,NaN,NaN,CA,https://foursquare.com/v/potala-organic-cafe/4...,"http://www.potala.us/,http://potala.us"
4,AVwd3yXEkufWRAb59-sH,2016-04-22T02:47:48Z,2018-09-10T21:00:49Z,1045 San Pablo Ave,"Restaurant,Asian/Pacific,Cafe,Vegetarian / Veg...",Accommodation & Food Services,Albany,US,"Thai,Asian/Pacific,Vegetarian",https://igx.4sqi.net/img/general/600x600/o_h1i...,us/ca/albany/1045sanpabloave/-1106202297,37.885131,-122.297013,http://www.singlepage.com/ruen-pair-authentic-...,13.95,3.75,NaN,USD,2016-04-22T02:48:00.000Z,With vinegar tahini beet dressing,Mixed Green Salad,https://foursquare.com/v/potala-organic-cafe/4...,Potala Organic Cafe,NaN,(510) 528-2375,94706,NaN,NaN,NaN,CA,https://foursquare.com/v/potala-organic-cafe/4...,"http://www.potala.us/,http://potala.us"
5,AVwddQkGkufWRAb56GvX,2016-03-24T10:25:20Z,2018-09-04T13:02:10Z,16411 Bernardo Center Dr,"Indian Restaurant,Restaurant,Caterers,Food Din...",Accommodation & Food Services,San Diego,US,"Vegetarian,Indian",https://irs3.4sqi.net/img/general/200x200/2099...,us/ca/sandiego/16411bernardocenterdr/1998744718,33.012662,-117.078590,http://www.citysearch.com/profile/menu/490729?...,2.49,2.49,Side Orders,USD,"2018-04-08T08:28:33.338Z,2018-07-01T12:12:35.4...",NaN,Mixed Pickles,https://www.allmenus.com/ca/san-diego/29208-pa...,Passage To India,"American Express,VISA",(858) 674-7500,92128,USD,25.0,40.0,CA,http://www.superpages.com/bp/san-diego-ca/pass...,http://passagetoindiasd.com
6,AVwddQkGkufWRAb56GvX,2016-03-24T10:25:20Z,2018-09-04T13:02:10Z,16411 Bernardo Center Dr,"Indian Restaurant,Restaurant,Caterers,Food Din...",Accommodation & Food Services,San Diego,US,"Vegetarian,Indian",https://irs3.4sqi.net/img/general/200x200/2099...,us/ca/sandiego/16411bernardocenterdr/1998744718,33.012662,-117.078590,http://www.citysearch.com/profile/menu/490729?...,6.99,6.99,Appetizers,USD,"2018-04-08T08:28:33.338Z,2018-07-01T12:12:35.4...",NaN,Cheese Pakora,https://www.allmenus.com/ca/san-diego/29208-pa...,Passage To India,"American Express,VISA",(858) 674-7500,92128,USD,25.0,40.0,CA,http://www.superpages.com/bp/san-diego-ca/pass...,http://passagetoindiasd.com
7,AVwddQkGkufWRAb56GvX,2016-03-24T10:25:20Z,2018-09-04T13:02:10Z,16411 Bernardo Center Dr,"Indian Restaurant,Restaurant,Caterers,Food Din...",Accommodation & Food Services,San Diego,US,"Vegetarian,Indian",https://irs3.4sqi.net/img/general/200x200/2099...,us/ca/sandiego/16411bernardocenterdr/1998744718,33.012662,-117.078590,http://www.citysearch.com/profile/menu/490729?...,2.99,2.99,Side Orders,USD,"2018-04-08T08:28:33.338Z,2018-07-01T12:12:35.4...",NaN,Mango Chutney,https://www.allmenus.com/ca/san-diego/29208-pa...,Passage To India,"American Express,VISA",(858) 674-7500,92128,USD,25.0,40.0,CA,http://www.superpages.com/bp/san-diego-ca/pass...,http://passagetoindiasd.com
8,AVwddQkGkufWRAb56GvX,2016-03-24T10:25:20Z,2018-09-04T13:02:10Z,16411 Bernardo Center Dr,"Indian Restaurant,Restaurant,Caterers,Food Din...",Accommodation & Food Services,San Diego,US,"Vegetarian,Indian",https://irs3.4sqi.net/img/general/200x200/2099...,us/ca/sandiego/16411bernardocenterdr/1998744718,33.012662,-117.078590,http://www.citysearch.com/profile/menu/490729?...,1.99,1.99,Traditional Tandoori Breads,USD,"2018-07-01T12:12:35.481Z,2018-04-08T08:28:33.3...",NaN,Tanoodri Roti,https://www.allmenus.com/ca/san-diego/29208-pa...,Passage To India,"American Express,VISA",(858) 674-7500,92128,USD,25.0,40.0,CA,http://www.superpages.com/bp/san-diego-ca/pass...,http://passagetoindiasd.com
9,AVwddQkGkufWRAb56GvX,2016-03-24T10:25:20Z,2018-09-04T13:02:10Z,16411 Bernardo Center Dr,"Indian Restaurant,Restaurant,Caterers,Food Din...",Accommodation & Food Services,San Diego,US,"Vegetarian,Indian",https://irs3.4sqi.net/img/general/200x200/2099...,us/ca/sandiego/16411bernardocenterdr/1998744718,33.012662,-117.078590,http://www.citysearch.com/profile/menu/490729?...,12.99,12.99,Tandoori Sizzlers,USD,"2018-04-08T08:28:33.338Z,2018-07-01T12:12:35.4...",NaN,Seekh Kebab,https://www.allmenus.com/ca/san-diego/29208-pa...,Passage To India,"American Express,VISA",(858) 674-7500,92128,USD,25.0,40.0,CA,http://www.superpages.com/bp/san-diego-ca/pass...,http://passagetoindiasd.com

In [29]:
df_1.fillna("Not Available",inplace=True)

In [30]:
df_1.sample(n=10)

,id,dateAdded,dateUpdated,address,categories,primaryCategories,city,country,cuisines,imageURLs,keys,latitude,longitude,menuPageURL,menus.amountMax,menus.amountMin,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,menus.sourceURLs,name,paymentTypes,phones,postalCode,priceRangeCurrency,priceRangeMin,priceRangeMax,province,sourceURLs,websites
8674,AVzBGDbxFcQ3k02bBeXU,2017-06-19T16:03:28Z,2018-04-30T13:47:29Z,146 6th St,"Restaurant,Bar,Beer Garden,American Restaurant...",Accommodation & Food Services,Pittsburgh,US,"American,Vegetarian Friendly,Gluten Free Optio...",https://media-cdn.tripadvisor.com/media/photo-...,us/pa/pittsburgh/1466thst/-1731303059,40.442822,-80.002382,http://www.citysearch.com/profile/menu/6012679...,5.00,5.00,Not Available,USD,"2018-01-22T07:26:42.609Z,2018-01-25T03:25:40.6...",Not Available,Arugula,https://foursquare.com/v/six-penn-kitchen/4ae3...,Six Penn Kitchen,"American Express,Debit Card,Discover,Mastercard",(412) 566-7366,15222,USD,25.0,40.0,PA,http://tripadvisor.com/Restaurant_Review-g5344...,http://www.sixpennkitchen.com
2435,AV8wUQH5IxWefVJwrQ-g,2017-10-18T16:27:40Z,2018-07-19T21:03:24Z,81 St Marks Pl,"Restaurant,Middle Eastern,Vegetarian",Accommodation & Food Services,New York,US,"Middle Eastern,Vegetarian",Not Available,us/ny/newyork/81stmarkspl/2035429109,40.727836,-73.985442,http://www.menupages.com/restaurants/cafe-rakk...,7.00,7.00,Soups ampamp Salads,USD,"2018-04-17T01:33:09.029Z,2018-04-10T10:14:20.5...",mixed greensampcomma tomato ampamp toasted pit...,21 Fattouch Salad,https://www.allmenus.com/ny/new-york/7745-cafe...,Cafe Rakka,Not Available,(212) 982-9166,10003,Not Available,Not Available,Not Available,NY,http://www.menupages.com/restaurants/cafe-rakk...,http://caferakka-nyc.com
9679,AVzA2-oLLD2H7whiWGUc,2017-06-19T14:57:36Z,2018-03-07T17:21:06Z,164 W 75th St,"Italian Restaurant,Bar,Restaurant,American,Ita...",Accommodation & Food Services,New York,US,"American,Italian,Healthy,Vegetarian",https://cdn3.gbot.me/photos/kQ/YY/1420747372/-...,us/ny/newyork/164w75thst/94551151,40.780323,-73.979965,http://www.singlepage.com/cesca-enoteca--tratt...,10.00,10.00,Not Available,USD,2018-02-26T20:38:18.662Z,Not Available,"Roasted Lemon Potatoes, Evoo",https://foursquare.com/v/cesca/4a8c835ef964a52...,'Cesca,"American Express,Mastercard,Visa",(212) 787-6300,10023,USD,40.0,55.0,NY,https://foursquare.com/v/cesca/4a8c835ef964a52...,"http://cescanyc.com,http://cescanyc.com/"
9955,AVwd88lK_7pvs4fz-toI,2016-03-28T05:35:40Z,2018-01-09T08:01:08Z,1335 W Thomas Rd,"Vegetarian / Vegan Restaurant,Restaurant,Medit...",Accommodation & Food Services,Phoenix,US,"Mediterranean,Vegetarian,Persian,Middle Eastern",https://cdn1.gbot.me/photos/6D/oK/1475183225/-...,us/az/phoenix/1335wthomasrd/-1848873742,33.480480,-112.090640,http://www.singlepage.com/persian-garden-cafe,7.00,7.00,Not Available,USD,"2017-12-17T23:32:00.000Z,2016-03-28T05:36:00.000Z",Not Available,Tabouli Salad,https://foursquare.com/v/persian-garden-cafe/4...,Persian Garden Cafe,Not Available,(602) 263-1915,85013,USD,40.0,55.0,AZ,https://foursquare.com/v/persian-garden-cafe/4...,"http://persiangardencafe.com,http://www.persia..."
3635,AVzA1JwXFcQ3k02bBXEW,2017-06-19T14:49:38Z,2018-07-19T20:48:18Z,156 5th Ave,"Restaurant,Bar,Vegetarian / Vegan Restaurant,V...",Accommodation & Food Services,Brooklyn,US,"Vegetarian,Eclectic and International,Kosher,V...",Not Available,us/ny/brooklyn/1565thave/112512632,40.678066,-73.979490,http://www.menupages.com/restaurants/the-v-spo...,10.00,10.00,Burritos,USD,"2018-05-20T09:23:57.069Z,2018-05-15T17:54:09.5...",Wholesome chunks of grilled housemade seitan t...,Chipotle Burritoavailable gf without wrap seit...,https://www.allmenus.com/ny/brooklyn/22632-v-s...,V Spot,Not Available,(718) 928-8778,11217,USD,25.0,40.0,NY,https://foursquare.com/v/the-v-spot/4a044291f9...,http://www.thevspotcafe.com
9531,AVwdUgLr_7pvs4fz4ott,2016-03-27T05:32:02Z,2018-03-08T11:36:10Z,1601 Elizabeth Ave,"New American Restaurant,American Restaurant,Se...",Accommodation & Food Services,Charlotte,US,"New American,Vegetarian,Italian",http://resizer.otstatic.com/v2/photos/medium/2...,us/nc/charlotte/1601elizabethave/-1580775961,35.213800,-80.826500,http://api.citygridmedia.com/content/places/v2...,7.00,7.00,Not Available,USD,"2018-02-11T14:53:16.875Z,2018-02-22T02:38:03.6...",Not Available,Belletoile Brie,https://foursquare.com/v/customshop/4b1991b4f9...,Customshop,"American Express,Discover,Mastercard,Visa",(704) 333-3396,28204,USD,40.0,55.0,NC,https://foursquare.com/v/customshop/4b1991b4f9...,http://www.customshopfood.com
1076,AVzA19T-FcQ3k02bBX1q,2017-06-19T14:53:09Z,2018-07-19T21:05:13Z,24 Pell St,"Chinese Restaurant,Restaurant,Vegetarian / Veg...",Accommodation & Food Services,New York,US,"Vegetarian,Dim Sum,Chinese",Not Available,us/ny/newyork/24pellst/-314427681,40.715022,-73.998173,http://www.menupages.com/restaurants/vegetaria...,9.95,9.95,Not Available,USD,"2018-01-03T09:36:46.875Z,2018-07-17T07:52:55.8...",Not Available,Bean Curd with Curry Sauce,http://www.menupages.com/restaurants/vegetaria...,Vegetarian Dim Sum House,Not Available,(212) 577-7176,10013,USD,0.0,25.0,NY,http://www.menupages.com/restaurants/vegetaria...,http://vegetariandimsumnyc.com
427,AVwegg55ByjofQCxy31X,2016-03-02T09:54:26Z,2018-07-20T18:13:49Z,2019 Post Oak Blvd,"Italian Restaurant,Restaurant,Take Out,Italian...",Accommodation & Food Services,Houston,US,"Seafood,Italian,Vegetarian,Deli and Sandwich",https://cdn4.gbot.me/photos/Ma/W8/1420747657/-...,us/tx/houston/2019postoakblvd/-578789913,29.744809,-95.460856,http://www.singlepage.com/maggianos-little-ita...,6.25,6.25,Not Available,USD,"2018-02-22T21:58:53.155Z,2018-03-02T08:19:10.4...",Not Available,Maggiano's Salad,https://foursquare.com/v/maggianos-little-ital...,Maggiano's Little Italy,Not Available,(713) 961-2700,77056,USD,25.0,40.0,TX,https://foursquare.com/v/maggianos-little-ital...,"http://www.maggianos.com/locations/,http://www..."
4516,AVwciQA0kufWRAb5wPST,2016-03-26T04:33:29Z,2018-07-19T09:40:09Z,605 Carlton Ave,"American (New),Restaurant,Local/Organic,New Am...",Accommodation & Food Services,Brooklyn,US,"American (New),New American,Local/Organic,Vege...",https://irs2.4sqi.net/img/general/200x200/8075...,us/ny/brooklyn/605carltonave/100890948,40.678982,-73.971618,http://www.menupages.com/restaurants/james/menu,8.00,8.00,Not Available,USD,2016-03-26T04:33:29Z,Kumquat compote,Grilled Lemon Pound Cake,https://foursquare.com/v/james/49baae9af964a52...,James,Not Available,(718) 942-4255,11238,USD,25.0,40.0,NY,https://foursquare.com/v/james/49baae9af964a52...,http://www.jamesrestaurantny.com
2511,AV8wURVe3-Khe5l_YO1L,2017-10-18T16:27:37Z,2018-07-19T21:02:47Z,7706 New Utrecht Ave,"Restaurant,Vegetarian,Chinese",Accommodation & Food Services,Brooklyn,US,"Vegetarian,Chinese",Not Available,us/ny/brooklyn/7706newutrechtave/-1931537875,40.614072,-74.000703,http://www.menupages.com/restaurants/orchid-dy...,11.95,11.95,Vegetable ampamp Tofu,USD,"2018-02-14T23:31:18.623Z,2018-04-17T09:29:30.7...",Not Available,207 Queenampaposs Bean Curd,https://www.allmenus.com/ny/brooklyn/478512-or...,Orchid Dynasty,Not Available,(718) 837-2017,11214,Not Available,Not Available,Not Available,NY,http://www.menupages.com/restaurants/orchid-dy...,Not Available

### We can check the popularity of vegetarian cusines based on postal code!

In [31]:
df_1['postalCode'].nunique()

146

#### Counting the number of vegetarian cuisines for each restuaran

In [32]:
df_1['primaryCategories'].nunique()

6

#### Some analysis around Primary Categories as well!

In [33]:
df_1['categories'].nunique()

166

In [34]:
df_1['cuisines'].nunique()

149

In [35]:
df_1['cuisines'] = df_1['cuisines'].apply(lambda x:x.lower())

In [36]:
df_1['categories'] = df_1['categories'].apply(lambda x:x.lower())

In [37]:
df_1['cuisines'].unique()

array(['thai,asian/pacific,vegetarian', 'vegetarian,indian',
       'smoothies and juices,vegetarian,healthy',
       'local/organic,vegan restaurants,smoothies and juices,vegetarian,healthy',
       'seafood,italian,vegetarian,deli and sandwich',
       'sushi,kosher,vegan', 'desserts,bakery and pastries,vegan',
       'american (new),vegetarian,coffee and tea,health food,vegan',
       'vegetarian,coffee and tea,bakery,desserts,bakery and pastries,vegan',
       'local/organic,vegetarian,coffee and tea,healthy,vegan',
       'vegetarian,dim sum,chinese', 'vegetarian,coffee and tea',
       'vegetarian,sandwiches', 'vegetarian,greek',
       'southeast asian,vegetarian,korean', 'vegetarian,thai',
       'vegetarian,salads', 'vegetarian,chinese',
       'vegetarian,kosher,sandwiches,kosher, vegetarian-friendly, sandwiches',
       'british (modern),vegetarian', 'deli food,vegetarian,indian',
       'middle eastern,vegetarian',
       'vegetarian,indian, vegetarian-friendly,indian',
       'cocktails,vegetarian,dim sum,chinese',
       'pizza,middle eastern,lebanese,vegetarian', 'vegetarian,korean',
       'local/organic,vegetarian,coffee and tea,vegan',
       'vegetarian,vietnamese', 'american (new),local/organic,vegetarian',
       'mexican,vegetarian',
       'middle eastern,smoothies and juices,vegetarian',
       'local/organic,smoothies and juices,vegetarian,healthy,vegan',
       'local/organic,smoothies and juices,vegetarian,kosher,healthy,vegan',
       'vegetarian,sushi,kosher,japanese', 'vegetarian,japanese,noodles',
       'vegetarian,sushi,japanese', 'vegetarian,japanese,healthy',
       'middle eastern,middle eastern, vegetarian-friendly,vegetarian',
       'middle eastern,vegetarian,sandwiches',
       'pizza,pizza, kosher, vegetarian-friendly,vegetarian,kosher',
       'pizza,vegetarian,kosher', 'vegetarian,african',
       'asian restaurants,take out,vietnamese restaurants,vegetarian,take out restaurants,vietnamese,asian,restaurants,vegan',
       'vegetarian,eclectic and international,kosher,vegan',
       'french,vegetarian,bistro', 'french,vegetarian',
       'italian,vegetarian', 'vegetarian,indian,desserts',
       'vegetarian,healthy', 'asian fusion,vegan',
       'pizza,middle eastern,vegetarian,salads,kosher',
       'mediterranean,vegetarian,coffee and tea,kosher',
       'smoothies and juices,vegetarian,coffee and tea,healthy,vegan',
       'breakfast and brunch,vegetarian,coffee and tea,hungarian,healthy,vegan',
       'mexican,middle eastern,vegetarian,turkish',
       'american (new),new american,local/organic,vegetarian',
       'healthy,salad,breakfast and brunch,american,soups,vegetarian friendly,vegan options,gluten free options',
       'health food,vegetarian', 'american, mexican, vegetarian',
       'vegetarian', 'indian,vegetarian',
       'mexican restaurants,latin american restaurants,vegetarian restaurants,vegan restaurants,caterers,restaurants,mexican,latin american,healthy,vegetarian,vegan',
       'mediterranean,vegetarian restaurants',
       'japanese,sushi,vegetarian',
       'traditional american,mexican,vegetarian',
       'chinese restaurants,caterers,bars,asian restaurants,bar and grills,vegan restaurants,restaurants,asian,healthy,chinese,vegetarian,vegan,taverns',
       'vegetarian,international,breakfast and brunch,vegan,asian',
       'thai,vegetarian',
       'traditional american,vegan,breakfast and brunch,vegan options',
       'indian,vegetarian friendly,vegan options,gluten free options,indian restaurants',
       'new american,health food,vegan,vegetarian,greek,mediterranean,tapas / small plates',
       'traditional american,seafood,vegetarian,vegetarian restaurants',
       'middle eastern and african,mediterranean,health food,vegan,vegetarian',
       'greek,seafood,mediterranean,vegetarian,mediterranean restaurants',
       'vegetarian,californian', 'vegetarian,vegetarian restaurants',
       'vegetarian,indian,vegetarian restaurants',
       'barbecue restaurants,american, vegetarian',
       'mexican,vegetarian,breakfast and brunch,diners',
       'vegetarian,chinese,dim sum,thai', 'vegetarian,caterers',
       'vegetarian,hot dogs', 'vegetarian,italian,pizza',
       'seafood,vegetarian,greek,indian',
       'fast food,japanese,asian,vegetarian friendly,vegan options',
       'breakfast and brunch,vegan',
       'ice cream and desserts,breakfast and brunch,coffee and tea,vegan,vegetarian',
       'indian restaurants,caterers,restaurants,indian,indian, vegan',
       'italian,pizza,vegetarian',
       'mexican restaurants,latin american restaurants,american restaurants,vegetarian restaurants,seafood restaurants,vegan restaurants,bar and grills,restaurants,mexican,american,latin american,seafood,healthy,vegetarian,vegan',
       'thai,thai restaurants,japanese,asian,sushi,vegetarian friendly,vegan options',
       'middle eastern,sandwiches,vegetarian', 'hamburgers,vegetarian',
       'american restaurants,caterers,coffee shops,vegetarian restaurants,vegan restaurants,breakfast brunch and lunch restaurants,,restaurants,american,cafeterias,breakfast,brunch and lunch,healthy,vegetarian,vegan',
       'vegetarian,chinese,thai',
       'mediterranean,mediterranean restaurants,middle eastern,lebanese,greek,vegetarian friendly,vegan options',
       'health food,vegetarian,hamburgers',
       'vegetarian,tapas / small plates', 'vegetarian,soups',
       'greek,vegetarian',
       'indian restaurants,middle eastern restaurants,asian restaurants,vegetarian restaurants,vegan restaurants,restaurants,asian,indian,healthy,vegetarian,middle eastern,vegan',
       'asian,sushi,japanese,seafood,vegetarian',
       'indian,indian, vegetarian, bar / lounge / bottle service',
       'mediterranean,vegetarian',
       'american,vegetarian friendly,vegan options,gluten free options,breakfast and brunch',
       'middle eastern and african,mediterranean,vegetarian,lebanese',
       'american,vegetarian', 'vegan,take out restaurants',
       'vegetarian restaurants',
       'chain restaurant,american , fast food , health , organic , smoothies , traditional , vegan , vegetarian , specialties',
       'italian, vegetarian,italian',
       'southern / soul,vegetarian,breakfast and brunch,vegan,american restaurants,caterers,restaurants',
       'vegan restaurants,caterers,bakeries,continental restaurants,breakfast brunch and lunch restaurants,,vegetarian restaurants,restaurants,breakfast,brunch and lunch,european,healthy,vegetarian,vegan,continental',
       'american,ice cream and desserts,vegetarian,vegan',
       'southern,vegetarian', 'mexican,seafood,vegetarian,southwestern',
       'ethiopian,vegetarian', 'traditional american,vegetarian',
       'vegetarian,chinese,chinese restaurants',
       'traditional american,american,soups,vegetarian friendly,vegan options,gluten free options',
       'mediterranean restaurants,greek restaurants,restaurants,greek,fast food,mediterranean,vegetarian friendly,vegan options',
       'traditional american,seafood,vegetarian,hamburgers',
       'vegetarian,breakfast and brunch,vegetarian friendly,juices',
       'vegetarian,mediterranean',
       'coffee shops,delicatessens,coffee and espresso restaurants,vegan restaurants,restaurants,vegetarian,coffee and tea,vegan',
       'eastern european,kosher,vegetarian',
       'thai,southeast asian,asian,vegetarian',
       'asian/pacific,health food,vegetarian,chinese',
       'vegetarian,breakfast and brunch',
       'traditional american,health food,vegetarian',
       'indian,vegetarian,take out restaurants',
       'italian,american,bar,vegetarian friendly,gluten free options,vegan options',
       'american,vegetarian friendly,gluten free options,vegan options',
       'american,breakfast and brunch,cafe,contemporary american, vegetarian / vegan, global, international',
       'persian,vegetarian restaurants',
       'middle eastern,lebanese,mediterranean,vegetarian friendly,vegan options,gluten free options',
       'new american,traditional american,american,vegetarian friendly,gluten free options,vegan options,northwest, american',
       'french,vegetarian,french, continental, american',
       'salads,vegetarian',
       'pizza,restaurants,italian,vegetarian friendly',
       'new american,vegetarian,italian',
       'american,italian,healthy,vegetarian',
       'health food restaurants,delicatessens,sandwich shops,vegetarian restaurants,vegan restaurants,restaurants,take out restaurants',
       'asian,sushi,japanese,vegetarian,steakhouse', 'chinese,vegetarian',
       'asian,thai,vegetarian friendly,asian/pacific,fusion',
       'american,seafood,wine bar,vegetarian friendly,vegan options,gluten free options,breakfast and brunch,bar,soups',
       'american,vegan,gluten free',
       'mediterranean,vegetarian,persian,middle eastern'], dtype=object)

In [38]:
pattern = '[a-z]+'

In [39]:
df_1['cuisines_list'] = df_1['cuisines'].apply(lambda x: x.split(','))

In [40]:
df_1['categories'] = df_1['categories'].apply(lambda x:x.split(','))

In [41]:
df_1['cuisines_list'][0]

['thai', 'asian/pacific', 'vegetarian']

In [42]:
df_1['categories'][0]

['restaurant',
 'asian/pacific',
 'cafe',
 'vegetarian / vegan restaurant',
 'vegetarian',
 'vegetarian vegan restaurant',
 'caf',
 'thai']

In [43]:
df_grby_city = df_1.groupby('city').agg(lambda cuisines_list:cuisines_list.tolist())

In [44]:
df_grby_city.shape

(81, 32)

In [45]:
def flatten(t):
    return [item for sublist in t for item in sublist]

In [46]:
df_grby_city['cuisines_list'] = df_grby_city['cuisines_list'].apply(lambda x:flatten(x))

In [47]:
df_grby_city['categories'] = df_grby_city['categories'].apply(lambda x:flatten(x))

In [48]:
df_grby_city['cuisines_list'][0]

['thai',
 'asian/pacific',
 'vegetarian',
 'thai',
 'asian/pacific',
 'vegetarian',
 'thai',
 'asian/pacific',
 'vegetarian',
 'thai',
 'asian/pacific',
 'vegetarian',
 'thai',
 'asian/pacific',
 'vegetarian']

In [49]:
df_grby_city['categories'][0]

['restaurant',
 'asian/pacific',
 'cafe',
 'vegetarian / vegan restaurant',
 'vegetarian',
 'vegetarian vegan restaurant',
 'caf',
 'thai',
 'restaurant',
 'asian/pacific',
 'cafe',
 'vegetarian / vegan restaurant',
 'vegetarian',
 'vegetarian vegan restaurant',
 'caf',
 'thai',
 'restaurant',
 'asian/pacific',
 'cafe',
 'vegetarian / vegan restaurant',
 'vegetarian',
 'vegetarian vegan restaurant',
 'caf',
 'thai',
 'restaurant',
 'asian/pacific',
 'cafe',
 'vegetarian / vegan restaurant',
 'vegetarian',
 'vegetarian vegan restaurant',
 'caf',
 'thai',
 'restaurant',
 'asian/pacific',
 'cafe',
 'vegetarian / vegan restaurant',
 'vegetarian',
 'vegetarian vegan restaurant',
 'caf',
 'thai']

In [50]:
def most_frequent(List):
    return max(set(List), key=List.count)

In [51]:
df_grby_city['most_common_cuisine'] = df_grby_city['cuisines_list'].apply(lambda x:most_frequent(x))

In [52]:
df_grby_city['most_common_category'] = df_grby_city['categories'].apply(lambda x:most_frequent(x))

In [53]:
df_grby_city['most_common_category']

city
Albany                                  caf
Arlington                health food stores
Asbury Park              breakfast & brunch
Astoria                          vegetarian
Atlanta                            american
                             ...
Waltham                         restaurants
Warren                          restaurants
Wellesley Hills                 restaurants
Westmont           family style restaurants
Woodside                         restaurant
Name: most_common_category, Length: 81, dtype: object

In [54]:
df_grby_city['categories'][0]

['restaurant',
 'asian/pacific',
 'cafe',
 'vegetarian / vegan restaurant',
 'vegetarian',
 'vegetarian vegan restaurant',
 'caf',
 'thai',
 'restaurant',
 'asian/pacific',
 'cafe',
 'vegetarian / vegan restaurant',
 'vegetarian',
 'vegetarian vegan restaurant',
 'caf',
 'thai',
 'restaurant',
 'asian/pacific',
 'cafe',
 'vegetarian / vegan restaurant',
 'vegetarian',
 'vegetarian vegan restaurant',
 'caf',
 'thai',
 'restaurant',
 'asian/pacific',
 'cafe',
 'vegetarian / vegan restaurant',
 'vegetarian',
 'vegetarian vegan restaurant',
 'caf',
 'thai',
 'restaurant',
 'asian/pacific',
 'cafe',
 'vegetarian / vegan restaurant',
 'vegetarian',
 'vegetarian vegan restaurant',
 'caf',
 'thai']

In [55]:
df_grby_city

,id,dateAdded,dateUpdated,address,categories,primaryCategories,country,cuisines,imageURLs,keys,latitude,longitude,menuPageURL,menus.amountMax,menus.amountMin,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,menus.sourceURLs,name,paymentTypes,phones,postalCode,priceRangeCurrency,priceRangeMin,priceRangeMax,province,sourceURLs,websites,cuisines_list,most_common_cuisine,most_common_category
city,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Albany,"[AVwd3yXEkufWRAb59-sH, AVwd3yXEkufWRAb59-sH, A...","[2016-04-22T02:47:48Z, 2016-04-22T02:47:48Z, 2...","[2018-09-10T21:00:49Z, 2018-09-10T21:00:49Z, 2...","[1045 San Pablo Ave, 1045 San Pablo Ave, 1045 ...","[restaurant, asian/pacific, cafe, vegetarian /...","[Accommodation & Food Services, Accommodation ...","[US, US, US, US, US]","[thai,asian/pacific,vegetarian, thai,asian/pac...",[https://igx.4sqi.net/img/general/600x600/o_h1...,"[us/ca/albany/1045sanpabloave/-1106202297, us/...","[37.885131, 37.885131, 37.885131, 37.885131, 3...","[-122.297013, -122.297013, -122.297013, -122.2...",[http://www.singlepage.com/ruen-pair-authentic...,"[13.95, 13.95, 13.95, 8.95, 13.95]","[3.75, 3.75, 3.75, 8.95, 3.75]","[Not Available, Not Available, Not Available, ...","[USD, USD, USD, USD, USD]","[2016-04-22T02:48:00.000Z, 2016-04-22T02:48:00...","[Squash, carrots, butternut squash and potato,...","[Baked Kabocha, Short Grain Brown Rice, Green ...",[https://foursquare.com/v/potala-organic-cafe/...,"[Potala Organic Cafe, Potala Organic Cafe, Pot...","[Not Available, Not Available, Not Available, ...","[(510) 528-2375, (510) 528-2375, (510) 528-237...","[94706, 94706, 94706, 94706, 94706]","[Not Available, Not Available, Not Available, ...","[Not Available, Not Available, Not Available, ...","[Not Available, Not Available, Not Available, ...","[CA, CA, CA, CA, CA]",[https://foursquare.com/v/potala-organic-cafe/...,"[http://www.potala.us/,http://potala.us, http:...","[thai, asian/pacific, vegetarian, thai, asian/...",vegetarian,caf
Arlington,"[AVwc7UHJkufWRAb50gE-, AVwc7UHJkufWRAb50gE-, A...","[2016-06-08T16:13:30Z, 2016-06-08T16:13:30Z, 2...","[2018-05-28T16:15:12Z, 2018-05-28T16:15:12Z, 2...","[1681 Crystal Square Arc, 1681 Crystal Square ...","[restaurant, health food stores, greek restaur...","[Accommodation & Food Services, Accommodation ...","[US, US, US, US, US, US, US, US, US, US, US, U...","[mediterranean restaurants,greek restaurants,r...",[https://i1.ypcdn.com/ypu/images/default-thumb...,[us/va/arlington/1681crystalsquarearc/21069464...,"[38.858192, 38.858192, 38.858192, 38.858192, 3...","[-77.051507, -77.051507, -77.051507, -77.05150...",[http://www.citysearch.com/profile/menu/379728...,"[6.49, 2.29, 1.29, 5.99, 5.29, 2.69, 5.99, 5.4...","[6.49, 0.79, 1.29, 5.99, 5.29, 2.69, 5.99, 5.4...","[Not Available, Not Available, Not Available, ...","[USD, USD, USD, USD, USD, USD, USD, USD, USD, ...","[2017-12-19T22:27:00.000Z,2017-10-28T23:23:00....","[Not Available, Not Available, Not Available, ...","[Stromboli, Desserts, Fresh Baked Muffins, Fal...",[https://foursquare.com/v/the-perfect-pita/4da...,"[The Perfect Pita, The Perfect Pita, The Perfe...","[discover,amex, discover,amex, discover,amex, ...","[(703) 418-6656, (703) 418-6656, (703) 418-665...","[22202, 22202, 22202, 22202, 22202, 22202, 222...","[USD, USD, USD, USD, USD, USD, USD, USD, USD, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25....","[VA, VA, VA, VA, VA, VA, VA, VA, VA, VA, VA, V...",[https://foursquare.com/v/the-perfect-pita/4da...,"[http://www.theperfectpita.com,http://api.city...","[mediterranean restaurants, greek restaurants,...",greek,health food stores
Asbury Park,"[AV1TsD-u-gnIPe8DWqIB, AV1TsD-u-gnIPe8DWqIB, A...","[2017-07-18T03:14:05Z, 2017-07-18T03:14:05Z, 2...","[2018-06-01T23:52:39Z, 2018-06-01T23:52:39Z, 2...","[311 Bond St, 311 Bond St, 311 Bond St, 311 Bo...","[natural food restaurants, southern / soul, ca...","[Accommodation & Food Services, Accommodation ...","[US, US, US, US, US, US, US, US, US, US, US, U...","[southern / soul,vegetarian,breakfast and brun...",[https://cdn3.gbot.me/photos/cR/Oc/1420628763/...,"[us/nj/asburypark/311bondst/-675358853, us/nj/...","[40.2168, 40.2168, 40.2168, 40.2168, 40.2168, ...","[-74.01176, -74.01176, -74.01176, -74.01176, -...","[http://www.singlepage.com/at-the-table, http:...","[4.95, 2.5, 4.95, 5.95, 5.0, 4.95, 2.5, 2.5, 3...","[4.95, 2.5, 4.95, 5.95, 5.0, 4.95, 2.5, 2.5, 3...","[Desserts, Drink Selection, Desserts, Kids Cor...","[USD, USD, USD, USD, USD, USD, USD, USD, USD, ...","[2018-03-30T23:29:11.904Z,2018-02-01T19:59:05....","[Not Available, Not Available, Not Available, ...","[Chocolate Cake, Coffee, Sweet Potato Pie, Mac...",[https://www.allmenus.com/nj/asbury-park/32844...,"[At the Table, At the Table, At the Table, At ...","[Not Available, Not Available, Not Available, ...","[(732) 455-5093, (732) 455-5093, (732) 455-509...","[04976, 07712, 07712, 07712, 07712, 07712, 077...","[USD, USD, USD, USD, USD, USD, USD, USD, USD, ...","[25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25....","[40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40....","[NJ, NJ, NJ, NJ, NJ, NJ, NJ, NJ, NJ, NJ, NJ, N...",[https://www.allmenus.com/nj/asbury-park/32844...,"[http://www.atthetablenj.com,http://www.atthet...","[southern / soul, vegetarian, breakfast and br...",breakfast and brunch,breakfast & brunch
Astoria,"[AWEIAFAq3-Khe5l_eG0V, AWEIAFAq3-Khe5l_eG0V, A...","[2018-01-18T06:37:09Z, 2018-01-18T06:37:09Z, 2...","[2018-07-19T20:48:19Z, 2018-07-19T20:48:19Z, 2...","[28-28 Steinway St, 28-28 Steinway St, 28-28 S...","[mediterranean restaurant, middle eastern, veg...","[Accommodation & Food Services, Accommodation ...","[US, US, US, US, US, US, US, US, US, US, US, U...","[middle eastern,vegetarian,sandwiches, middle ...","[Not Available, Not Available, Not Available, ...","[us/ny/astoria/28-28steinwayst/-47414860, us/n...","[40.764755, 40.764755, 40.764755, 40.764755, 4...","[-73.914467, -73.914467, -73.914467, -73.91446...",[http://www.menupages.com/restaurants/la-shish...,"[1.5, 6.0, 5.5, 2.0, 1.5, 4.0, 2.0, 4.0, 5.0, ...","[1.5, 6.0, 5.5, 2.0, 1.5, 4.0, 2.0, 4.0, 5.0, ...","[Not Available, Not Available, Not Available, ...","[USD, USD, USD, USD, USD, USD, USD, USD, USD, ...","[2018-07-16T21:34:07.834Z,2018-04-24T15:32:32....","[Not Available, Not Available, Not Available, ...","[Kibbeh Ball, Falafel, Beans, Daily Soup, Lahm...",[http://www.menupages.com/restaurants/la-shish...,"[La Shish, La Shish, La Shish, La Shish, La Sh...","[Not Available, Not Available, Not Available, ...","[(718) 278-2828, (718) 278-2828, (718) 278-282...","[11103, 11103, 11103, 11103, 11103, 11103, 111...","[USD, USD, USD, USD, USD, USD, USD, USD, USD, ...","[25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25....","[40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40....","[NY, NY, NY, NY, NY, NY, NY, NY, NY, NY, NY, N...",[https://foursquare.com/v/la-shish/4d975c78b18...,"[Not Available, Not Available, Not Available, ...","[middle eastern, vegetarian, sandwiches, middl...",vegetarian,vegetarian
Atlanta,"[AV1TrQ0xLD2H7whiaJUw, AV1TrQ0xLD2H7whiaJUw, A...","[2017-07-18T03:10:36Z, 2017-07-18T03:10:36Z, 2...","[2018-06-08T00:47:10Z, 2018-06-08T00:47:10Z, 2...","[879 Ralph David Abernathy SW, 879 Ralph David...","[restaurant, american, vegetarian, restaurant,...","[Accommodation & Food Services, Accommodation ...","[US, US, US, US, US]","[american,vegetarian, american,vegetarian, ame...",[https://cdn2.gbot.me/photos/Zs/xQ/1437272969/...,[us/ga/atlanta/879ralphdavidabernathysw/-99167...,"[33.738157, 33.738157, 33.738157, 33.738157, 3...","[-84.416542, -84.416542, -84.416542, -84.41654...",[http://www.singlepage.com/soul-vegetarian-res...,"[7.95, 2.5, 1.8, 3.4, 6.45]","[7.95, 2.5, 1.8, 3.4, 6.45]","[Entrees, Appetizers, Desserts, Appetizers, En...","[USD, USD, USD, USD, USD]","[2018-06-06T01:12:51.954Z,2018-02-12T11:40:02....","[Not Available, Not Available, Not Available, ...","[Basketsampcomma Saleem 2 Item, Onion Ring Bas...",[https://www.allmenus.com/ga/atlanta/434841-so...,"[Soul Vegetarian, Soul Vegetarian, Soul Vegeta...","[Not Available, Not Available, Not Available, ...","[(404) 752-5194, (404) 752-5194, (404) 752-519...","[30310, 30310, 30310, 30310, 30310]","[Not Available, Not Available, Not Available, ...","[Not Available, Not Available, Not Available, ...","[Not Available, Not Available, Not Available, ...","[GA, GA, GA, GA, GA]",[https://www.trip.com/atlanta/restaurants/soul...,"[http://www.vegetariantimes.com/, http://www.v...","[american, vegetarian, american, vegetarian, a...",american,american
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Waltham,[AVwd-hCF_7pvs4fz-8Qq],[2017-01-09T20:23:14Z],[2018-06-03T09:43:53Z],[361 Moody St],"[restaurant, restaurants]",[Accommodation & Food Services],[US],"[italian,vegetarian]",[Not Available],[us/ma/waltham/361moodyst/-1328131808],[42.369996],[-71.237132],[http://www.citysearch.com/profile/menu/479396...,[19.0],[19.0],[Pasta],[USD],"[2018-04-08T15:18:52.555Z,2018-02-13T08:14:03....",[Not Available],[Tortellini Bolognese],[https://www.allmenus.com/ma/waltham/171557-tu...,[Tuscan Grill],"[Mastercard,Discover,Visa,Travelers Check,Amer...",[(781) 891-5486],[02139],[Not Available],[Not Available],[Not Available],[MA],[https://www.allmenus.com/ma/waltham/171557-tu...,[Not Available],"[italian, vegetarian]",vegetarian,restaurants
Warren,"[AVwdoBjHByjofQCxq9pR, AVwdoBjHByjofQCxq9pR, A...","[2015-10-23T02:51:52Z, 2015-10-23T02:51:52Z, 2...","[2018-06-16T18:39:00Z, 2018-06-16T18:39:00Z, 2...","[5709 E 12 Mile Rd, 5709 E 12 Mile Rd, 5709 E ...","[mediterranean restaurant, restaurant, restaur...","[Accommodation & Food Services, Accommodation ...","[US, US, US, US, US, US, US, US, US, US, US, U...","[mediterranean,mediterranean restaurants,middl...",[https://irs0.4sqi.net/img/general/200x200/384...,"[us/mi/warren/5709e12milerd/1742367992, us/mi/...","[42.506671, 42.506671, 42.506671, 42.506671, 4...","[-83.049498, -83.049498, -83.049498, -83.04949...",[http://www.citysearch.com/profile/menu/652237...,"[12.99, 4.25, 3.25, 9.99, 8.99, 1.75, 8.99, 8....","[12.99, 4.25, 3.25, 9.99, 8.99, 1.75, 8.99, 8....","[Sides and Desserts, Raw Juice and Beverages, ...","[USD, USD, USD, USD, USD, USD, USD, USD, USD, ...","[2018-05-20T22:16:09.591Z,2018-04-13T14:16:56....","[Not Available, Carrot orange beet radish and...","[Bread Dz Half, Cobra, Hommous and Tabbouli, H...",[https://www.allmenus.com/mi/warren/392712-oas...,"[Oasis Mediterranean Cuisine, Oasis Mediterran...","[Not Available, Not Available, Not Available, ...","[(586) 619-7551, (586) 619-7551, (586) 619-755...","[48092, 48092, 48092, 48092, 48092, 48092, 480...","[USD, USD, USD, USD, USD, USD, USD, USD, USD, ...","[25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25....","[40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40....","[MI, MI, MI, MI, MI, MI, MI, MI, MI, MI, MI, M...",[http://www.citysearch.com/profile/652237730/w...,"[http://www.oasiscuisine.com, http://www.oasis...","[mediterranean, mediterranean restaurants, mid...",greek,restaurants
Wellesley Hills,"[AV4u0H0ARxPSIh2Rex-0, AV4u0H0ARxPSIh2Rex-0, A...","[2017-08-29T16:24:33Z, 2017-08-29T16:24:33Z, 2...","[2018-06-20T03:33:41Z, 2018-06-20T03:33:41Z, 2...","[257 Washington St, 257 Washington St, 257 Was...","[restaurant, thai restaurant, restaurants, res...","[Accommodation & Food Services, Accommodation ...","[US, US, US, US, US, US, US, US, US, US, US, U...","[vegetarian,thai, vegetarian,thai, vegetarian,...","[Not Available, Not Available, Not Available, ...",[us/ma/wellesleyhills/257washingtonst/12684582...,"[42.313014, 42.313014, 42.313014, 42.313014, 4...","[-71.273897, -71.273897, -71.273897, -71.27389...",[http://www.citysearch.com/profile/menu/342614...,"[10.95, 10.95, 5.75, 10.95, 5.75, 7.95, 3.5, 7...","[10.95, 10.95, 5.75, 10.95, 5.75, 7.95, 3.5, 7...","[Woking Noodle Dishes Dinner, Coconut Curry Di...","[USD, USD, USD, USD, USD, USD, USD, USD, USD, ...","[2018-06-10T22:05:02.561Z,2018-06-04T22:45:58....",[This traditional pad Thai is made with crysta...,"[33 Crystal Pad Thai Noodles Dinner, 20 Massam...",[https://www.allmenus.com/ma/wellesley/141579-...,"[Coconut Thai Cafe, Coconut Thai Cafe, Coconut...","[Cash,Mastercard,Visa, Cash,Mastercard,Visa, C...","[(781) 235-8255, (781) 235-8255, (781) 235-825...","[02139, 02139, 02139, 02139, 02481, 02481, 024...","[USD, USD, USD, USD, USD, USD, USD, USD, USD, ...","[25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25....","[40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40....","[MA, MA, MA, MA, MA, MA, MA, MA, MA, MA, MA, M...",[https://foursquare.com/v/coconut-thai-cafe/4a...,"[http://www.coconut-cafe.com, http://www.cocon...","[vegetarian, thai, vegetarian, thai, vegetaria...",vegetarian,restaurants
Westmont,"[AVwc5NFFIN2L1WUfqC_B, AVwc5NFFIN2L1WUfqC_B, A...","[2014-01-06T05:32:50Z, 2014-01-06T05:32:50Z, 2...","[2018-06-29T19:35:47Z, 2018-06-29T19:35:47Z, 2...","[655 N Cass Ave, 655 N Cass Ave, 655 N Cass Av...","[asian restaurants, restaurant, family style r...","[Accommodation & Food Services, Accommodation ...","[US, US, US, US, US, US, US, US, US, US, US, U...","[vegetarian,indian,vegetarian restaurants, veg...","[Not Available, Not Available, Not Available, ...","[us/il/westmont/655ncassave/-1280403174, us/il...","[41.810579, 41.810579, 41.810579, 41.810579, 4...","[-87.975883, -87.975883, -87.975883, -87.97588...",[http://api.citygridmedia.com/content/places/v...,"[11.95, 2.95, 5.95, 2.0, 10.95, 10.95, 3.95, 1...","[11.95, 2.95, 5.95, 2.0, 10.95, 10.95, 3.95, 1...","[Curries, Beverages, Appetizers, Extras, Speci...","[USD, USD, USD, USD, USD, USD, USD, USD, USD, ...","[2018-06-26T10:07:01.348Z,2018-05-13T04:43:26....",[Home made cheese cubes cooked with spinach to...,"[Sag Paneer, Tea, Potato Bonda, Yogurt, Specia...",[https://www.allmenus.com/il/westmont/309980-s...,"[Shree Restaurant, Shree Restaurant, Shree Res...","[American Express,Mastercard,Visa,discover, Am...","[(630) 655-1021, (630) 655-1021, (630) 655-102...","[60559, 60559, 60559, 60559, 60559, 60559, 605...","[Not Available, Not Available, Not Available, ...","[Not Available, Not Available, Not Available, ...","[Not Available, Not Available, Not Available, ...","[IL, IL, IL, IL, IL, IL, IL, IL, IL, IL, IL, I...",[http://www.citysearch.com/profile/3626241/wes...,"[http://www.shreerestaurant.com, http://www.sh...","[vegetarian, indian, vegetarian restaurants, v...",vegetarian,family style restaurants
Woodside,"[AV8wUnVr3-Khe5l_YO8q, AV8wUnVr3-Khe5l_YO8q, A...","[2017-10-18T16:27:40Z, 2017-10-18T16:27:40Z, 2...","[2018-06-29T19:30:41Z, 2018-06-29T19:30:41Z, 2...","[4908 43rd Ave, 4908 43rd Ave, 4908 43rd Ave, ...","[restaurant, vegetarian, thai, restaurant, veg...","[Accommodation & Food Services, Accommodation ...","[US, US, US, US, US, US, US, US, US, US, US, U...","[thai,vegetarian, thai,vegetarian, thai,vegeta...","[Not Available, Not Available, Not Available, ...","[us/ny/woodside/490843rdave/1579856241, us/ny/...","[40.744326, 40.744326, 40.744326, 40.744326, 4...","[-73.915236, -73.915236, -73.915236, -73.91523...",[http://www.menupages.com/restaurants/i-am-tha...,"[4.95, 7.0, 4.95, 4.95, 2.5, 2.0, 4.0, 8.95, 8...","[4.95, 7.0, 4.95, 4.95, 2.5, 2.0, 4.0, 8.95, 8...","[Vegetarian Appetizers, Soup, Salad Bowls, Veg...","[USD, USD, USD, USD, USD, USD, USD, USD, USD, ...","[2018-04-03T10:34:12.104Z,2018-05-13T04:54:49....",[fried tofu served with sweet chili sauce and ...,"[Fried Tofu, Vegetable Ginger Soup, Thai Salad...",[https://www.allmenus.com/ny/woodside/308631-i...,"[I Am Thai, I Am Thai, I Am Thai, I Am Thai, I...","[Not Available, Not Available, Not Available, ...","[(718) 457-7700, (718) 457-7700, (718) 457-770...","[11377, 11377, 11377, 11377, 11377, 11377, 113...","[Not Available, Not Available, Not Available, ...","[Not Available, Not Available, Not Available, ...","[Not Available, Not Available, Not Available, ...","[NY, NY, NY, NY, NY, NY, NY, NY, NY, NY, NY, N...",[http://www.menupages.com/restaurants/i-am-tha...,"[http://www.iamthairestaurant.com, http://www....","[thai, vegetarian, thai, vegetarian, thai, veg...",vegetarian,restaurant

In [56]:
df_grby_city.columns

Index(['id', 'dateAdded', 'dateUpdated', 'address', 'categories',
       'primaryCategories', 'country', 'cuisines', 'imageURLs', 'keys',
       'latitude', 'longitude', 'menuPageURL', 'menus.amountMax',
       'menus.amountMin', 'menus.category', 'menus.currency', 'menus.dateSeen',
       'menus.description', 'menus.name', 'menus.sourceURLs', 'name',
       'paymentTypes', 'phones', 'postalCode', 'priceRangeCurrency',
       'priceRangeMin', 'priceRangeMax', 'province', 'sourceURLs', 'websites',
       'cuisines_list', 'most_common_cuisine', 'most_common_category'],
      dtype='object')

In [57]:
df_grby_city.reset_index(inplace=True)

In [58]:
df_modified = df_grby_city[['city','categories','cuisines','cuisines_list','most_common_cuisine','most_common_category']]

In [59]:
df_modified.shape

(81, 6)

In [60]:
df_modified

,city,categories,cuisines,cuisines_list,most_common_cuisine,most_common_category
0,Albany,"[restaurant, asian/pacific, cafe, vegetarian /...","[thai,asian/pacific,vegetarian, thai,asian/pac...","[thai, asian/pacific, vegetarian, thai, asian/...",vegetarian,caf
1,Arlington,"[restaurant, health food stores, greek restaur...","[mediterranean restaurants,greek restaurants,r...","[mediterranean restaurants, greek restaurants,...",greek,health food stores
2,Asbury Park,"[natural food restaurants, southern / soul, ca...","[southern / soul,vegetarian,breakfast and brun...","[southern / soul, vegetarian, breakfast and br...",breakfast and brunch,breakfast & brunch
3,Astoria,"[mediterranean restaurant, middle eastern, veg...","[middle eastern,vegetarian,sandwiches, middle ...","[middle eastern, vegetarian, sandwiches, middl...",vegetarian,vegetarian
4,Atlanta,"[restaurant, american, vegetarian, restaurant,...","[american,vegetarian, american,vegetarian, ame...","[american, vegetarian, american, vegetarian, a...",american,american
...,...,...,...,...,...,...
76,Waltham,"[restaurant, restaurants]","[italian,vegetarian]","[italian, vegetarian]",vegetarian,restaurants
77,Warren,"[mediterranean restaurant, restaurant, restaur...","[mediterranean,mediterranean restaurants,middl...","[mediterranean, mediterranean restaurants, mid...",greek,restaurants
78,Wellesley Hills,"[restaurant, thai restaurant, restaurants, res...","[vegetarian,thai, vegetarian,thai, vegetarian,...","[vegetarian, thai, vegetarian, thai, vegetaria...",vegetarian,restaurants
79,Westmont,"[asian restaurants, restaurant, family style r...","[vegetarian,indian,vegetarian restaurants, veg...","[vegetarian, indian, vegetarian restaurants, v...",vegetarian,family style restaurants
80,Woodside,"[restaurant, vegetarian, thai, restaurant, veg...","[thai,vegetarian, thai,vegetarian, thai,vegeta...","[thai, vegetarian, thai, vegetarian, thai, veg...",vegetarian,restaurant

In [61]:
df_modified.to_csv('cleaned_cuisines_and_categories.csv',index=False)

In [63]:
df_grby_city['cuisines_list'][0]

['thai,asian/pacific,vegetarian',
 'thai,asian/pacific,vegetarian',
 'thai,asian/pacific,vegetarian',
 'thai,asian/pacific,vegetarian',
 'thai,asian/pacific,vegetarian']

In [24]:
df_2 = pd.read_csv('../data/vegetarian_restaurants_US_datafiniti.csv')

In [25]:
df_2.shape

(18155, 29)

In [26]:
df_2.head(n=10)

,address,categories,city,claimed,country,cuisines,dateOpened,dateUpdated,descriptions,facebookPageURL,features,hours,images,isClosed,key,lat,languages,long,menus,menuURL,name,paymentTypes,phones,postalCode,priceRange,province,sic,twitter,websites
0,2871 Gulf To Bay Blvd,"American, American (new), Clearwater Restauran...",Clearwater,NaN,US,NaN,NaN,2014-02-01T04:41:06Z,"Tags: American (New), American, and Trendy Sta...",NaN,NaN,NaN,NaN,NaN,us/fl/clearwater/2871gulftobayblvd,27.971165,NaN,-82.696938,"[{""descriptions"":""A combination of diced ham a...",NaN,Village Inn Restaurant and Bakery,NaN,7277964988,33759,NaN,FL,8423,NaN,NaN
1,605 W Main St,Caf and Sandwich Place,Louisville,NaN,US,"Vegetarian, Delicatessen",NaN,2016-07-23T22:37:24Z,"Atlantic No. 5, Louisville: See 4 unbiased rev...",NaN,"[{""key"":""Value Rating"",""value"":""3.5 of 5 stars...","[{""day"":""Mon - Fri"",""hour"":""7:00 AM - 4:00 PM""...",https://irs2.4sqi.net/img/general/200x200/2973...,NaN,us/ky/louisville/605wmainst,38.257020,NaN,-85.760013,"[{""descriptions"":""Mexican coke, ale 8, q soda,...",NaN,Atlantic No. 5,Yes,5028833398,40202,USD 25.00-40.00,KY,NaN,NaN,atlanticno5.com
2,3803 9th St S W,"American, Barbecue, Puyallup Restaurants, Barb...",Puyallup,NaN,US,NaN,NaN,2015-11-19T22:22:31Z,"Description: Famous Dave's is a Barbecue , Am...",NaN,NaN,NaN,NaN,NaN,us/wa/puyallup/38039thstsw/98451436,47.154828,NaN,-122.303992,"[{""descriptions"":""create your own full slab. p...",NaN,Famous Dave's,NaN,2536040340,98373,USD 10.00 - USD 15.00,WA,5610,NaN,http://famousdaves.com
3,30 S Main St,"Coffee & Tea, Restaurant, Restaurants, Bar, Am...",Oberlin,NaN,US,"Coffee & Tea, Restaurants, American, Bar, Pu...",NaN,2016-06-20T17:47:10Z,"The Feve, Oberlin: See 170 unbiased reviews of...",NaN,"[{""key"":""AKA:"",""value"":""Feve The""},{""key"":""Val...","[{""day"":""Sat - Sun"",""hour"":""9:30 am - 2:30 am""...",https://irs1.4sqi.net/img/general/200x200/1541...,NaN,us/oh/oberlin/30smainst,41.290823,NaN,-82.217640,NaN,/oberlin-oh/mip/the-feve-8940755/menu,The Feve,"mastercard, amex, discover, Yes, visa","[""4407741978"",""4197741978"",""4407753064""]",44074,USD 25.00-40.00,OH,NaN,NaN,http://www.thefeve.com
4,55 Crescent Dr,Sandwich Place and Fast Food Restaurant,Pleasant Hill,yellowpages.com,US,"Take Out Restaurants, Asian Restaurants, Resta...",NaN,2016-07-23T23:55:05Z,"[""https://www.zagat.com/r/yalla-mediterranean-...",NaN,"[{""key"":""Price Range "",""value"":""Below Average""}]","[{""day"":""Monday "",""hour"":""11:00am - 9:00pm ""},...",http://storage.googleapis.com/zgt-photos/0x808...,NaN,us/ca/pleasanthill/55crescentdr,37.945663,NaN,-122.061997,"[{""descriptions"":""greek salad and rice pilaf t...",/pleasant-hill-ca/mip/yalla-mediterranean-5061...,Quiznos,"master card, visa",9258258644,94523,$,CA,NaN,quiznos,http://www.yallamedi.com/
5,2243 Richmond Ave,"English Restaurant, Caf, and Breakfast Spot",Houston,NaN,US,"Coffee Shops, American Restaurants, Restaurant...",NaN,2016-07-23T23:24:12Z,"[""https://www.zagat.com/r/hobbit-cafe-houston""]",NaN,"[{""key"":""Other Information"",""value"":""Parking: ...","[{""day"":""Mon–Thu"",""hour"":""11:00 AM–9:30 PM""},{...",https://irs0.4sqi.net/img/general/200x200/7108...,NaN,us/tx/houston/2243richmondave,29.733600,NaN,-95.414600,"[{""descriptions"":[""Spring mix with fresh and t...",/houston-tx/mip/hobbit-cafe-22358589/menu,Hobbit Cafe,"check, discover, cash, amex, all major credit ...","[""7135265460""]","[""77098""]",USD 25.00-40.00,TX,NaN,cafehobbit,http://www.myhobbitcafe.com/
6,8007 State Rt 31,"Pizza, Restaurants",Bridgeport,NaN,US,"New York Style Pizza, Pizza By The Slice, Home...",2011-01-01T12:00:00Z,2015-11-19T22:21:54Z,Check Out Our Full Menu At: www.myfamiliapizza...,NaN,NaN,NaN,NaN,NaN,us/ny/bridgeport/8007statert31,NaN,NaN,NaN,NaN,NaN,Familia Pizza,NaN,3156339909,13030,NaN,NY,5610,NaN,http://www.myfamiliapizza.com
7,415 Thompson Ln,"Nashville Restaurants, Glencliff Estates, Rest...",Nashville,NaN,US,"African, Ethiopian, Vegetarian",NaN,2013-09-16T03:03:44Z,Tags: nothing yet. tagging it. -->,NaN,NaN,NaN,NaN,NaN,us/tn/nashville/415thompsonln,36.119880,NaN,-86.718505,NaN,NaN,Lalibela Ethiopian Cuisine,NaN,6153320710,37211-2212,USD 5 - USD 10,TN,5610,NaN,NaN
8,217 W Beloit St,"Orfordville Restaurants, Italian / Pizza / Veg...",Orfordville,NaN,US,NaN,NaN,2013-09-15T02:05:19Z,"Tags: Italian, Pizza, and Family Style Stats: ...",NaN,NaN,NaN,NaN,NaN,us/wi/orfordville/217wbeloitst,42.635024,NaN,-89.268167,NaN,NaN,Villa Pizza (closed),NaN,6088799929,53576,NaN,WI,5610,NaN,NaN
9,309 N Lamar Blvd,Restaurants,Oxford,NaN,US,"American, Vegetarian, Healthy",NaN,2013-09-18T03:45:30Z,NaN,NaN,NaN,NaN,NaN,NaN,us/ms/oxford/309nlamarblvd/-562612811,34.368020,NaN,-89.518390,NaN,NaN,The Pita Pit,NaN,6622383535,38655-3201,NaN,MS,5610,NaN,NaN

In [27]:
df_2['country'].unique()

array(['US'], dtype=object)

In [28]:
df_2['claimed'].unique()

array([nan, 'yellowpages.com', 'foursquare.com',
       'foursquare.com, yellowpages.com',
       'yellowpages.com, foursquare.com', 'homestars.com',
       'insiderpages.com'], dtype=object)

#### Use this data for missing values

In [29]:
df_2['priceRange'].value_counts()

$$                      1827
USD 25.00-40.00         1417
$                       1150
USD 0.00-25.00           757
USD 0.00 - USD 30.00     505
                        ...
USD 7 - USD 29             1
USD 8 - USD 24             1
USD 2 - USD 20             1
USD 3 - USD 18             1
USD 18 - USD 35            1
Name: priceRange, Length: 151, dtype: int64

In [30]:
df_2['claimed'].value_counts()

yellowpages.com                    596
foursquare.com                     212
foursquare.com, yellowpages.com      4
yellowpages.com, foursquare.com      4
insiderpages.com                     3
homestars.com                        1
Name: claimed, dtype: int64

In [ ]:
df_2

#### reading the next data frame

In [34]:
df_3, meta = pyreadstat.read_sav("../data/Faunalytics-Current-Former-Veg-Study-Dataset-All-Respondents-Original-Variables.sav")

In [35]:
df_3.sample(n=10)

,id,token,submitdate,startlanguage,startdate,datestamp,ALL_1_1,ALL_1_2,ALL_1_3,ALL_1_4,ALL_1_5,ALL_1_6,ALL_1_7,ALL_1_8,ALL_1_9,ALL_1_10,ALL_1_11,ALL_1_13,ALL_1_14,ALL_1_15,ALL_1_16,ALL_1_17,ALL_1_18,ALL_1_19,OMNIVORES_1,OMNIVORES_2,UNVER_VEGN_REC_3,UNVER_VEG_REC_4_1,UNVER_VEG_REC_4_2,UNVER_VEG_REC_4_3,UNVER_VEG_REC_4_4,UNVER_VEG_REC_4_5,UNVER_VEG_REC_4_6,UNVER_VEG_REC_4_7,UNVER_VEG_REC_4_8,UNVER_VEG_REC_4_9,UNVER_VEG_REC_4_10,UNVER_VEG_REC_4_11,UNVER_VEG_REC_4_13,UNVER_VEG_REC_4_14,UNVER_VEG_REC_4_15,UNVER_VEG_REC_4_16,UNVER_VEG_REC_4_17,UNVER_VEG_REC_4_18,UNVER_VEG_REC_4_19,UNVER_VEGAN_REC_4_1,UNVER_VEGAN_REC_4_2,UNVER_VEGAN_REC_4_3,UNVER_VEGAN_REC_4_4,UNVER_VEGAN_REC_4_5,...,VEG_1_8,VEG_1_9,VEG_1_10,VEG_1_11,VEG_1_12,VEG_1_13,VEG_1_14,VEG_1_15,VEGAN_1_1,VEGAN_1_2,VEGAN_1_3,VEGAN_1_4,VEGAN_1_5,VEGAN_1_6,VEGAN_1_7,VEGAN_1_8,VEGAN_1_9,VEGAN_1_10,VEGAN_1_11,VEGAN_1_12,VEGAN_1_13,V460,V461,VEG_2_SQ001,VEG_2_SQ002,VEG_2_SQ003,VEG_2_SQ004,VEG_2_SQ005,VEG_2_SQ006,VEG_2_SQ007,VEG_2_SQ008,VEG_2_SQ009,VEG_2_SQ010,VEGAN_2_SQ001,VEGAN_2_SQ002,VEGAN_2_SQ003,VEGAN_2_SQ004,VEGAN_2_SQ005,VEGAN_2_SQ006,VEGAN_2_SQ007,VEGAN_2_SQ008,VEGAN_2_SQ009,VEGAN_2_SQ010,ALL_1,ALL_2,ALL_3,ALL_4,ALL_5,ALL_6,ALL_7
10990,11920.0,,NaT,en,2014-05-17 10:19:29,2014-05-17 10:20:08,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,2.0,2.0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,,,,,,,,,,,,,,,,,,,,,,,NaN,,,NaN,NaN
6971,7547.0,,NaT,en,2014-05-13 12:07:40,2014-05-13 12:09:09,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,2.0,2.0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,,,,,,,,,,,,,,,,,,,,,,,NaN,,,NaN,NaN
6145,6662.0,,NaT,en,2014-05-12 10:10:16,2014-05-12 10:10:41,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,,,,,,,,,,,,,,,,,,,,,,,NaN,,,NaN,NaN
4628,5039.0,,NaT,en,2014-05-10 08:02:54,2014-05-10 08:04:19,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,2.0,2.0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,,,,,,,,,,,,,,,,,,,,,,,NaN,,,NaN,NaN
1650,1839.0,,NaT,en,2014-05-08 11:51:47,2014-05-08 11:53:07,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,2.0,2.0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,,,,,,,,,,,,,,,,,,,,,,,NaN,,,NaN,NaN
5828,6320.0,,NaT,en,2014-05-12 09:10:57,2014-05-12 09:12:25,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,2.0,2.0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,,,,,,,,,,,,,,,,,,,,,,,NaN,,,NaN,NaN
773,884.0,,NaT,en,2014-05-07 18:13:48,2014-05-07 18:32:56,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,2.0,2.0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,,,,,,,,,,,,,,,,,,,,,,,NaN,,,NaN,NaN
1849,2049.0,,2014-05-08 12:52:47,en,2014-05-08 12:50:11,2014-05-08 12:52:47,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0,,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,,,,,,,,,,,,,,,,,,,,,66,A2,5.0,A6,A3,8.0,2.0
7179,7778.0,,NaT,en,2014-05-13 15:36:43,2014-05-13 15:37:42,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,2.0,2.0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,,,,,,,,,,,,,,,,,,,,,,,NaN,,,NaN,NaN
10989,11919.0,,NaT,en,2014-05-17 10:16:33,2014-05-17 10:18:38,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,2.0,2.0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,,,,,,,,,,,,,,,,,,,,,,,NaN,,,NaN,NaN

In [36]:
meta

In [37]:
df_1.sample(n=10)

,id,dateAdded,dateUpdated,address,categories,primaryCategories,city,claimed,country,cuisines,descriptions.dateSeen,descriptions.sourceURLs,descriptions.value,facebookPageURL,features.key,features.value,hours.day,hours.dept,hours.hour,imageURLs,isClosed,keys,languagesSpoken,latitude,longitude,menuPageURL,menus.amountMax,menus.amountMin,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,menus.sourceURLs,name,paymentTypes,phones,postalCode,priceRangeCurrency,priceRangeMin,priceRangeMax,province,sic,sourceURLs,twitter,websites,yearOpened
4198,AV8wURBz3-Khe5l_YO1B,2017-10-18T16:27:41Z,2018-07-19T09:43:40Z,1395 Lexington Ave,"Mediterranean,Restaurant,Vegetarian,Coffee and...",Accommodation & Food Services,New York,NaN,US,"Mediterranean,Vegetarian,Coffee and Tea,Kosher",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,us/ny/newyork/1395lexingtonave/-910163161,NaN,40.782752,-73.952907,http://www.menupages.com/restaurants/effys-isr...,2.00,2.00,NaN,USD,"2017-10-19T14:31:00.000Z,2017-11-27T09:44:00.0...",NaN,Snapple,http://www.menupages.com/restaurants/effys-isr...,Effy's Israeli Cafe,NaN,(212) 415-5552,10128,NaN,NaN,NaN,NY,NaN,http://www.menupages.com/restaurants/effys-isr...,NaN,NaN,NaN
2258,AV8wU3vyIxWefVJwrRJM,2017-10-18T16:27:40Z,2018-07-19T21:03:55Z,413 Amsterdam Ave,"Restaurant,Vegetarian,Indian",Accommodation & Food Services,New York,NaN,US,"Vegetarian,Indian",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,us/ny/newyork/413amsterdamave/244936590,NaN,40.783649,-73.977937,http://www.menupages.com/restaurants/saravanaa...,13.49,13.49,Dosa Corner,USD,"2018-04-14T02:02:15.215Z,2018-04-16T04:39:41.950Z",Red chili chutney spread on thin rice and lent...,Mysore Onion Masala Dosa,https://www.allmenus.com/ny/new-york/301435-sa...,Saravanaa Bhavan,NaN,(212) 721-7755,10024,NaN,NaN,NaN,NY,NaN,http://www.menupages.com/restaurants/saravanaa...,NaN,NaN,NaN
7845,AVwdkgt9kufWRAb57MLk,2016-01-12T23:23:53Z,2018-05-20T14:04:10Z,1515 S 4th St,"Coffee Shop,Delicatessens,Vegetarian / Vegan R...",Accommodation & Food Services,Philadelphia,yellowpages.com,US,"Coffee Shops,Delicatessens,Coffee and Espresso...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://i1.ypcdn.com/ypu/images/default-thumbn...,NaN,us/pa/philadelphia/1515s4thst/1196284493,NaN,39.929111,-75.151957,http://www.singlepage.com/grindcore-house,4.00,4.00,Drinks,USD,2018-05-11T18:03:02.232Z,NaN,GTampaposs Synergy Kombucha,https://www.allmenus.com/pa/philadelphia/36063...,Grindcore House,"amex,visa",(215) 839-3333,19147,USD,25.0,40.0,PA,NaN,https://www.trip.com/philadelphia/restaurants/...,grindcorehouse,"http://www.grindcorehouse.com,http://www.faceb...",NaN
4103,AVweZHSikufWRAb5CgtN,2015-11-02T17:36:57Z,2018-07-19T09:44:23Z,1376 Lexington Ave,"Pizza,Falafel Restaurant,Restaurant,Middle Eas...",Accommodation & Food Services,New York,NaN,US,"Pizza,Middle Eastern,Vegetarian,Salads,Kosher",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://irs2.4sqi.net/img/general/200x200/6634...,NaN,us/ny/newyork/1376lexingtonave/-2064339646,NaN,40.782644,-73.953488,http://www.menupages.com/restaurants/sabas-piz...,2.99,2.99,NaN,USD,"2018-06-02T15:12:05.085Z,2017-12-17T09:01:24.9...",NaN,Classic Cheese Slice,http://www.menupages.com/restaurants/sabas-piz...,Saba's Pizza,NaN,(212) 987-9130,10128,USD,0.0,25.0,NY,NaN,http://www.menupages.com/restaurants/sabas-piz...,NaN,https://sabaspizzanyc.com,NaN
3139,AVwc1YGZkufWRAb5zgwb,2016-03-26T04:33:33Z,2018-07-19T20:53:50Z,659 Washington Ave,"Restaurant,Sushi Restaurant,Vegetarian,Sushi,J...",Accommodation & Food Services,Brooklyn,NaN,US,"Vegetarian,Sushi,Japanese",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://irs3.4sqi.net/img/general/200x200/4486...,NaN,us/ny/brooklyn/659washingtonave/102224,NaN,40.677572,-73.963703,http://www.menupages.com/restaurants/gen/menu,9.00,9.00,NaN,USD,"2016-03-26T04:33:33Z,2016-05-15T21:50:52Z",NaN,Vegetable Tempura Udon or Soba,https://foursquare.com/v/gen/49f50c9ff964a5208...,Gen,NaN,(718) 398-3550,11238,USD,25.0,40.0,NY,NaN,https://foursquare.com/v/gen/49f50c9ff964a5208...,gensushi,"http://genrestaurant.biz,http://www.genrestaur...",NaN
8009,AWE7OJzxa4HuVbedNZRV,2018-01-28T05:19:38Z,2018-05-14T00:17:16Z,72-27 37th Ave,"Indian Restaurant,Vegetarian,Indian,Desserts",Accommodation & Food Services,Jackson Heights,NaN,US,"Vegetarian,Indian,Desserts",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,us/ny/jacksonheights/72-2737thave/-1518144516,NaN,40.748847,-73.892875,http://www.menupages.com/restaurants/rajbhog-s...,3.49,3.49,NaN,USD,"2018-01-23T20:51:11.057Z,2018-01-28T18:52:03.6...",NaN,Rajbhog Mix,https://foursquare.com/v/rajbhog-sweets/4afdcf...,Rajbhog Sweets,NaN,(718) 458-8512,11372,USD,0.0,25.0,NY,NaN,https://foursquare.com/v/rajbhog-sweets/4afdcf...,NaN,http://rajbhog.com,NaN
1401,AVzA1io5-gnIPe8DScus,2017-06-19T14:51:19Z,2018-07-19T21:04:48Z,12 E 32nd St,"Southeast Asian,Restaurant,Vegetarian / Vegan ...",Accommodation & Food Services,New York,NaN,US,"Southeast Asian,Vegetarian,Korean",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://cdn2.gbot.me/photos/Vy/Qm/1361915081/-...,NaN,us/ny/newyork/12e32ndst/692882753,NaN,40.747272,-73.986576,http://www.menupages.com/restaurants/hangawi/menu,9.00,9.00,NaN,USD,"2017-11-22T11:01:23.472Z,2017-12-27T10:03:21.6...",NaN,Gluten Free Ice Cream,http://www.menupages.com/restaurants/hangawi/menu,Hangawi,"Mastercard,Visa,American Express,Diners Club",(212) 213-0077,10016,USD,40.0,55.0,NY,NaN,https://foursquare.com/v/hangawi/3fd66200f964a...,NaN,"http://hangawirestaurant.com,http://www.hangaw...",NaN
5882,AVwc9W3-_7pvs4fz0xJ7,2016-03-23T03:18:59Z,2018-06-29T19:24:31Z,1460 W Chicago Ave,"Restaurant,Vegetarian / Vegan Restaurant,Veget...",Accommodation & Food Services,Chicago,NaN,US,"Vegetarian,Caterers",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://cdn3.gbot.me/photos/BA/Qj/1322826063/_...,NaN,us/il/chicago/1460wchicagoave/-313674269,NaN,41.896114,-87.664651,http://www.singlepage.com/green-zebra,9.00,9.00,Specialty Beer,USD,"2018-04-29T18:32:28.845Z,2018-04-05T11:41:07.6...",ampaposyetiampaposampcomma great divide brewin...,Russian Imperial Stout,https://www.allmenus.com/il/chicago/21441-gree...,Green Zebra,Mastercard,(312) 243-7100,60622,USD,40.0,55.0,IL,NaN,http://www.citysearch.com/profile/38715595/chi...,NaN,"http://www.greenzebrachicago.com,http://www.gr...",NaN
5674,AVwc3k4JByjofQCxjEfY,2016-03-27T05:39:16Z,2018-06-30T09:18:55Z,2531 Chain Bridge Rd,"Asian Restaurants,Restaurant,Chinese Restauran...",Accommodation & Food Services,Vienna,NaN,US,"Vegetarian,Vegetarian Restaurants",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://storage.googleapis.com/zgt-photos/0x89b...,NaN,us/va/vienna/2531chainbridgerd/688384642,NaN,38.892958,-77.275703,http://www.citysearch.com/profile/menu/1047355...,6.95,6.95,Rice,USD,"2018-04-16T03:34:36.052Z,2018-02-04T02:52:24.2...",chunk of soy proteinampcomma stewed wzucchinia...,8 Curry Paradise,https://www.allmenus.com/va/vienna/297323-sunf...,Sunflower Vegetarian Restaurant,amex,(703) 319-3888,22181,USD,0.0,25.0,VA,NaN,https://foursquare.com/v/sunflower-vegetarian-...,NaN,"http://www.crystalsunflower.com,http://api.cit...",NaN
3462,AV5aKKwe3-Khe5l_Vk3W,2017-09-07T02:21:36Z,2018-07-19T20:48:18Z,342 E 6th St,"Asian Restaurants,Restaurant,Vietnamese Restau...",Accommodation & Food Services,New York,yellowpages.com,US,"Asian Restaurants,Take Out,Vietnamese Restaura...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://i1.ypcdn.com/ypu/images/default-thumbn...,NaN,us/ny/newyork/342e6thst/-52189514,NaN,40.726478,-73.986611,http://www.menupages.com/restaurants/lan-cafe/...,2.50,2.50,Tea,USD,"2018-04-10T09:58:38.273Z,2018-04-08T08:19:43.3...",NaN,Hot Dry Chrysanthemum Tea,https://www.allmenus.com/ny/new-york/60262-lan...,Lan Cafe,"master card,amex,visa",(212) 228-8325,10003,NaN,NaN,NaN,NY,NaN,http://www.menupages.com/restaurants/lan-cafe/...,NaN,http://lancafenyc.com/,NaN

In [38]:
df_2.sample(n=10)

,address,categories,city,claimed,country,cuisines,dateOpened,dateUpdated,descriptions,facebookPageURL,features,hours,images,isClosed,key,lat,languages,long,menus,menuURL,name,paymentTypes,phones,postalCode,priceRange,province,sic,twitter,websites
9829,1451 O St,"Salad Place, Vegetarian / Vegan Restaurant, an...",Lincoln,NaN,US,NaN,NaN,2016-08-18T22:04:49Z,NaN,NaN,NaN,"[{""day"":""Mon���Wed"",""hour"":""11:00 AM���7:00 PM...",NaN,NaN,us/ne/lincoln/1451ost,NaN,NaN,NaN,"[{""descriptions"":"". "",""name"":""Mandarin Oranges...",NaN,"Grateful Greens, Abloom",Yes (incl. Discover & MasterCard),"[""4022618388""]",68508,USD 0.00-25.00,NE,NaN,", gratefulgreens",NaN
10969,316 E Judge Perez Dr,Restaurant,Chalmette,NaN,US,"Pizza, Vegetarian",NaN,2016-03-23T04:22:16Z,"Domino's Pizza, Chalmette: See unbiased review...",NaN,NaN,"[{""day"":""Saturday"",""hour"":""10:00 am - 1:00 am""}]",https://static.tacdn.com/img2/x.gif,NaN,us/la/chalmette/316ejudgeperezdr/-1055723171,29.941296,NaN,-89.960940,NaN,NaN,Domino's Pizza,NaN,5042793010,70043,NaN,LA,NaN,NaN,http://www.dominos.com
7604,Village On High,"Vegetarian Restaurants, Health Food Restaurant...",Millville,yellowpages.com,US,"Vegetarian Restaurants, Health Food Restaurant...",NaN,2016-08-19T00:33:41Z,NaN,NaN,NaN,"[{""day"":""Fri - Sat"",""hour"":""11:00 am - 9:00 pm...",NaN,NaN,us/nj/millville/villageonhigh,39.395380,NaN,-75.037750,NaN,NaN,Wildflower Earthly Vegan Fare,cash only,8562657955,8332,NaN,NJ,NaN,NaN,http://wildflowervegan.com
6344,3111 S Shepherd Dr,"Noodle House, Asian Restaurant, Soup Place",Houston,NaN,US,"Take Out Restaurants, Asian Restaurants, Cater...",NaN,2016-09-17T07:02:08Z,"[""https://www.zagat.com/r/jennis-noodle-house-...",NaN,"[{""key"":""AKA:"",""value"":""Jennis Noodle House""},...","[{""day"":""Mon - Sat"",""hour"":""11:00 AM - 10:00 P...",http://i3.ypcdn.com/blob/93bc56afac6f793bf6edf...,NaN,us/tx/houston/3111sshepherddr,29.738152,NaN,-95.410347,"[{""descriptions"":""To any entree"",""name"":""Add S...",/houston-tx/mip/jennis-noodle-house-1966414/menu,Jenni's Noodle House,"mastercard, amex, discover, visa",7135237600,77098,USD 25.00-40.00,TX,NaN,NaN,http://www.noodlesrule.com
6414,139 Ashland St,"Italian, North Adams Restaurants, Italian / Ve...",N Adams,NaN,US,NaN,NaN,2013-10-03T01:05:58Z,Tags: Italian,NaN,NaN,NaN,NaN,NaN,us/ma/nadams/139ashlandst,42.695029,NaN,-73.109733,"[{""descriptions"":""fit for the Sunday table any...",NaN,Red Sauce,NaN,4136622200,1247,NaN,MA,5610,NaN,NaN
6745,104 N Runger Ave,"American, Pizza, Sloan Restaurants, Pizza / Am...",Sloan,NaN,US,NaN,NaN,2013-10-03T01:10:23Z,"Tags: Pizza, American, and Family Style Stats:...",NaN,NaN,NaN,NaN,NaN,us/ia/sloan/104nrungerave,42.400310,NaN,-96.362875,"[{""descriptions"":""beef, onions, pickles, two c...",NaN,Pizza Ranch,NaN,7123244800,51055,NaN,IA,5610,NaN,NaN
14761,812 Paseo Del Pueblo Norte,"Taos Restaurants, Vegetarian / Middle Eastern",Taos,NaN,US,NaN,NaN,2013-09-16T03:28:36Z,Tags: Vegetarian and Middle Eastern,NaN,NaN,NaN,NaN,NaN,us/nm/taos/812paseodelpueblonorte/2079241212,36.421885,NaN,-105.572889,NaN,NaN,Sheva Cafe,NaN,5057379290,87571-6481,NaN,NM,5610,NaN,NaN
9359,222 4th St,Vegetarian / Vegan Restaurant,Henderson,NaN,US,NaN,NaN,2016-06-20T15:36:36Z,NaN,NaN,NaN,NaN,NaN,NaN,us/tn/henderson/2224thst,35.447110,NaN,-88.638690,NaN,NaN,The Vegan & Vegetarian Place,NaN,NaN,38340,NaN,TN,NaN,NaN,NaN
5245,2330 Jacaman Rd,Restaurant,Laredo,NaN,US,"Vegetarian, Vegan, Vegan",NaN,2016-05-24T05:54:29Z,"El Quinto Sol, Laredo: See 13 unbiased reviews...",NaN,"[{""key"":""Food Rating"",""value"":""5 of 5 stars""},...","[{""day"":""Saturday"",""hour"":""7:30 pm - 10:30 pm""...",http://media-cdn.tripadvisor.com/media/photo-t...,NaN,us/tx/laredo/2330jacamanrd,27.562872,NaN,-99.453730,NaN,NaN,El Quinto Sol,NaN,NaN,NaN,NaN,TX,NaN,NaN,NaN
15729,1501 N Cahuenga Blvd,Coffee Shop and Vegetarian / Vegan Restaurant,NaN,NaN,US,NaN,NaN,2016-05-19T12:44:46Z,NaN,NaN,NaN,"[{""day"":""Sat"",""hour"":""8:00 AM - 9:00 PM""},{""da...",NaN,NaN,us/null/null/1501ncahuengablvd,NaN,NaN,NaN,"[""Granola, Vanilla Yogurt, Fresh Seasonal Berr...",NaN,Groundwork Coffee Co.,NaN,3238710107,NaN,USD 0.00-25.00,NaN,NaN,groundworkcoffe,NaN

In [39]:
df = pd.concat([df_1,df_2])

In [40]:
df.shape

(28155, 59)

In [42]:
df.columns

Index(['id', 'dateAdded', 'dateUpdated', 'address', 'categories',
       'primaryCategories', 'city', 'claimed', 'country', 'cuisines',
       'descriptions.dateSeen', 'descriptions.sourceURLs',
       'descriptions.value', 'facebookPageURL', 'features.key',
       'features.value', 'hours.day', 'hours.dept', 'hours.hour', 'imageURLs',
       'isClosed', 'keys', 'languagesSpoken', 'latitude', 'longitude',
       'menuPageURL', 'menus.amountMax', 'menus.amountMin', 'menus.category',
       'menus.currency', 'menus.dateSeen', 'menus.description', 'menus.name',
       'menus.sourceURLs', 'name', 'paymentTypes', 'phones', 'postalCode',
       'priceRangeCurrency', 'priceRangeMin', 'priceRangeMax', 'province',
       'sic', 'sourceURLs', 'twitter', 'websites', 'yearOpened', 'dateOpened',
       'descriptions', 'features', 'hours', 'images', 'key', 'lat',
       'languages', 'long', 'menus', 'menuURL', 'priceRange'],
      dtype='object')