In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pltt

In [2]:
df = pd.read_csv('../project_data/vegetarian_restaurants_US_datafiniti.csv')

In [3]:
df.shape

(18155, 29)

In [4]:
df.sample(n=10)

,address,categories,city,claimed,country,cuisines,dateOpened,dateUpdated,descriptions,facebookPageURL,...,menuURL,name,paymentTypes,phones,postalCode,priceRange,province,sic,twitter,websites
4995,928 State St,Vegetarian / Vegan Restaurant,Lockport,NaN,US,NaN,NaN,2016-07-19T01:01:21Z,NaN,NaN,...,NaN,Vegan Cafe,NaN,"[""8155579868""]",60441,NaN,IL,NaN,NaN,rawvegancafe.org
4605,2085 National Rd,Restaurant,Wheeling,NaN,US,"Cafe, Vegetarian, Vegan",NaN,2016-05-25T06:58:41Z,"Grindhouse Coffee & Tea Company, Wheeling: See...",NaN,...,NaN,Grindhouse Coffee Tea Company - Closed,NaN,3042425767,26003,NaN,WV,NaN,NaN,NaN
11786,2025 Wilshire Blvd,Vegetarian / Vegan Restaurant,Santa Monica,NaN,US,NaN,NaN,2016-09-07T02:30:56Z,NaN,NaN,...,NaN,Veggie Grill,Yes (incl. Discover & Visa),"[""3108291155""]",90403,USD 0.00-25.00,CA,NaN,veggiegrill,http://veggiegrill.com
16830,2950 28th St S E,"American, Coffee & Tea, Salads, Soups, Grand R...",Grand Rapids,NaN,US,NaN,NaN,2013-10-03T01:05:13Z,"Tags: Coffee & Tea, Convenience Items, and Veg...",NaN,...,NaN,Wild Bean Cafe,NaN,6163018888,49512,NaN,MI,1079,NaN,http://wildbeancafe.com
16958,247 W Park Ave,"[""Take Out Restaurants"",""Fast Food Restaurants...",Thibodaux,yellowpages.com,US,"[""Take Out Restaurants"",""Fast Food Restaurants...",NaN,2016-08-01T18:24:50Z,"[""http://www.yellowpages.com/thibodaux-la/mip/...",NaN,...,http://www.yellowpages.com/thibodaux-la/mip/do...,Domino's Pizza,"master card, visa, diners club, amex, discover...","[""9854481700""]","[""70301""]",$,LA,5610,", dominos",https://www.dominos.com/en/?redirect=homepage&...
3204,714 Us 74 Br,"Rockingham Restaurants, American / Vegan / Veg...",Rockingham,NaN,US,NaN,NaN,2013-09-16T03:35:41Z,"Description: FATZ is a American , Vegan , and...",NaN,...,NaN,Fatz,NaN,9105824040,28379,NaN,NC,5610,NaN,NaN
1489,2340 E Griggs Ave,"American, Restaurants, Las Cruces Restaurants,...",Las Cruces,NaN,US,American,NaN,2013-10-02T05:44:58Z,"Tags: American, Family Style, and Kid Friendly...",NaN,...,NaN,Furr's,NaN,5056479515,88001,NaN,NM,NaN,NaN,NaN
13585,Boston City Hall,Food Truck and Vegetarian / Vegan Restaurant,Boston,NaN,US,NaN,NaN,2016-07-23T22:52:28Z,NaN,NaN,...,NaN,Clover Food Truck (city Hall),NaN,NaN,2109,NaN,MA,NaN,clovergov,NaN
5447,NaN,"Bakery, Vegetarian / Vegan Restaurant, and Cof...",NaN,NaN,US,NaN,NaN,2016-06-14T02:46:42Z,NaN,NaN,...,NaN,Duck's Cosmic Kitchen,NaN,4043718823,30030,NaN,NaN,NaN,duckscosmic,NaN
14264,2300 Pleasant Hill Rd,"American, Deli, Duluth Restaurants, Deli / Ame...",Duluth,NaN,US,NaN,NaN,2013-10-03T01:14:58Z,"Tags: Deli, American, and Vegan Stats: 39 dish...",NaN,...,NaN,My Friend's Place,NaN,7708138228,30096,NaN,GA,8423,NaN,NaN

In [5]:
df.columns

Index(['address', 'categories', 'city', 'claimed', 'country', 'cuisines',
       'dateOpened', 'dateUpdated', 'descriptions', 'facebookPageURL',
       'features', 'hours', 'images', 'isClosed', 'key', 'lat', 'languages',
       'long', 'menus', 'menuURL', 'name', 'paymentTypes', 'phones',
       'postalCode', 'priceRange', 'province', 'sic', 'twitter', 'websites'],
      dtype='object')

In [6]:
df['dateUpdated'].min()

'2012-06-30T16:42:39Z'

In [8]:
df['menus'][2]

'[{"descriptions":"create your own full slab. pair up a 1/2 slab of hicko4ry-smoked st. louis-style spareribs with a 1/2 slab of our lip smackin baby backs.","name":"Rib N Rib Bbq Combo"},{"descriptions":"St. louis-style spareribs are just the starter. add fried chicken tenders, chili-roasted corn fritters, onion strings and traditional or boneless wings tossed in your choice of sauce.","name":"Dave\'s Sampler Platter"},{"descriptions":"slathered with devil\'s spit bbq sauce and topped with pepper-jack cheese, jalapeno bacon and hell fire pickle chips","name":"Devil\'s Spit Burger"},{"descriptions":"smoked for up to 12 hours and chopped to order, our award-winning bbq pork is juicier than a georgia peach.","name":"Georgia Chopped Pork"},{"descriptions":"tri-tip seasoned with our own sweet and spicy rub, hickory smoked then sliced and served over texas toast.","name":"Smoked Sirloin Tri-tip Platter"},{"descriptions":"georgia chopped pork, texas beef brisket, barbeque Pulled chicken with jack cheese sandwiches served with your choice of one side.","name":"Real Que Sandwich Specials"},{"descriptions":"over a full pound of the meatiest portion of the ribs, grilled and slathered in rich & sassy bbq sauce and chopped into tender pieces.","name":"Rib Tips"},{"descriptions":"grilled chicken breast with pepper jack cheese, piled high with fried onion strings and topped with new orleans style remoulade sauce.","name":"Cajun Chicken Sandwich"},{"descriptions":"a devilishly good hot sauce loaded with chili peppers and spices. heat level - medium high.","name":"Devil\'s Spit"},{"descriptions":"loaded baked potato topped with choice of texas beef brisket, georgia chopped pork or barbeque pulled chicken.","name":"Bbq Stuffed Potato"},{"descriptions":"lean cuts, grilled and lightly-seasoned are sinfully delicious, melt in your mouth tender.","name":"Steak Tenderloins"},{"descriptions":"serves 2-3 a half portion of the all-american bbq feast.","name":"Feast For Two (serves 2-3)"},{"descriptions":"the sandwich that separates the men from the boys. texas beef brisket and zesty hot link sausage, sliced thin, piled high and crowned with hell-fire pickles.","name":"Texas Manhandler"},{"descriptions":"you get: 60 chicken wings, 2 1/2 pounds texas beef brisket, 2 1/2 pounds georgia chopped pork, 15 buns and 4 quart size sides","name":"Smokin\' Que\' (serves 15)"},{"descriptions":"you get choice of bbq sandwich, plus country roasted or bbq chicken, two side choices and a corn bread muffin.","name":"Piglet Plus (15 Person Minimum)"},{"descriptions":["smoked and spicy a mouthful of hollers on a bun.","a real mouthful of hollers twelve ounces of hot link sausage best served with an ice cold beer to douse the flames."],"name":"Hot Link Sausage"},{"descriptions":"careful, this cow kicks a seasoned burger slathered with devil\'s spit bbq sauce and topped with melted pepper jack cheese, jalapeno bacon and hell fire pickles.","name":"Devil S Spit Burger"},{"descriptions":["a full pound of tips, hickory smoked and fire grilled with a memphis-style dry rub. served on a bed of our famous fries with a side of jalapeno pickled red onions, hell fire pickles and our southside bbq sauce.","a full pound of tips, hickory smoked and fire grilled with a memphis style dry rub. served with a side of jalapeno pickled red onions, hell fire pickles and our southside bbq sauce."],"name":"Southside Rib Tips"},{"descriptions":"varies","name":"Drunkin\' Apples"},{"descriptions":"what a catch a beautiful 6-ounce salmon fillet grilled to perfection and drizzled with our honey chipotle lime glaze.","name":"Citrus Grilled Salmon"},{"descriptions":"piled high with hand-seasoned, hickory smoked texas beef brisket.","name":"Texas Beef Brisket Sandwich"},{"descriptions":"lemon pepper marinated half chicken, roasted and char grilled to perfection.","name":"Country Roasted Chicken"},{"descriptions":"our award winning wings tossed in your choice of sauce.","name":"Traditional or Boneless Wings"},{"descriptions":"bleu cheese lovers, meet the cheeseburger of your dreams a flame-grilled patty on a toasted bun with lettuce, tomato, red onion and topped with both tangy bleu cheese dressing and crumbles.","name":"True Bleu Cheeseburger"},{"descriptions":"varies","name":"Xxl Rib \'\'the Big Slab\'\' -12 Bone"},{"descriptions":"a zesty slaw that s pineapple sweet with a hint of horseradish.","name":"Creamy Coleslaw"},{"descriptions":"grilled pineapple blended in a sauce with habanero peppers. hot, sweet and dangerously delicious. heat level - medium high.","name":"Pineapple Rage"},{"descriptions":"makes our devil\'s spit sauce seem downright tame in comparison. warning: that sizzlin sound might just be your tongue. heat level - explosive.","name":"Wilbur\'s Revenge"},{"descriptions":"a full slab of st. louis-style spareribs, a whole country-roasted chicken, 1/2 lb. of either texas beef brisket or georgia chopped pork, creamy coleslaw, famous fries, wilbur beans, four corn-on-the-cob and four corn bread muffins. served family-style for 4-6.","name":"All American Bbq Feast"},{"descriptions":"served with corn bread muffin and your choice of two sides. (1/2 slab).","name":"Halvin My Baby"},{"descriptions":"beer battered and breaded with a special blend of cornmeal and panko breadcrumbs. served with our house made spicy pickle tartar sauce.","name":"Beer Battered Cod"},{"descriptions":"you get st. louis style spareribs, choice of country roasted or bbq chicken, 2 side choices, cornbread muffin and mini dessert.","name":"Lil\' Pig Plus (15 Person Minimum)"},{"descriptions":"beer battered and breaded with a special blend of cornmeal and panko breadcrumbs. served on a toasted bun and topped with sharp american cheese and our house made spicy pickle tartar sauce.","name":"Beer Battered Cod Sandwich"},{"descriptions":"our traditional buffalo-style sauce with a nice flavorful kick. heat level - medium.","name":"Buffalo"},{"descriptions":"varies","name":"Buffalo Chicken Wings"},{"descriptions":"potatoes with red onion, celery, hard cooked egg, mayonnaise and a hint of mustard.","name":"Potato Salad"},{"descriptions":"you\'ll get: choice of 3 meats, 2 sides and corn bread muffin.","name":"The Big Pig (15 Person Minimum)"},{"descriptions":"iceberg and romaine tossed with cilantro, shredded cheddar, tomato, roasted corn, black beans, fried tortilla strips and our own lime chipotle ranch dressing then drizzled with rich & sassy. with hot grilled chicken breast.","name":"Bbq Chopped Salad"},{"descriptions":"honey chipotle lime glaze gives these plump, luscious shrimp skewers a real kick in the tail.","name":"Citrus Grilled Shrimp"},{"descriptions":"a juicy ground beef patty beneath a pile of georgia chopped pork with two strips of jalapeno bacon, melted sharp american cheese and our signature beam & cola bbq sauce.","name":"Ultimate Bbq Burger"},{"descriptions":"sliced hickory-smoked tri-tip served on a toasted hoagie roll with texas pit horseradish sauce.","name":"Smoked Sirloin Tri-tip Sandwich"},{"descriptions":"includes: 24 chicken wings, 2 pounds of georgia chopped pork, 1/2 dozen hamburger buns, choice of 2 pint size sides.","name":"\'que Combo (serves 6)"},{"descriptions":"hand pulled chicken tossed in rich & sassy and topped with melted jack cheese.","name":"Barbeque Pulled Chicken Sandwich"},{"descriptions":"our country-roasted chicken flame kissed and slathered with rich & sassy.","name":"Barbeque Chicken"},{"descriptions":"includes: 24 chicken wings, 3 pounds of georgia chopped pork, 1 & 1/2 country roasted chickens, 10 hamburger buns, choice of 2 quart size sides.","name":"Backyard Bbq (serves 10)"},{"descriptions":"topped with choice of georgia chopped pork, texas beef brisket or bbq chicken. tossed with bacon, cheddar cheese, diced tomatoes, potato sticks, and our homemade honey bbq dressing","name":"Dave\'s Sassy Bbq Salad"},{"descriptions":"dig into the ultimate caesar salad: featuring crisp romaine lettuce freshly tossed in dave\'s own caesar dressing and topped with chilled, hickory smoked salmon.","name":"Smoked Salmon Caesar Salad"},{"descriptions":"topped with jack cheese and two strips of bacon","name":"Hickory Chicken Breast"},{"descriptions":"varies","name":"Chicken Wild Rice Soup"},{"descriptions":"a full slab of spareribs, a whole chicken, 1/2 pound of either texas beef brisket or georgia chopped pork, coleslaw, famous fries, wilbur beans, four corn-on-the-cob and four corn bread muffins.","name":"All American Bbq Feast (serves 4-5)"},{"descriptions":"you\'ll get: world famous st. louis style spareribs, country roasted or bbq chicken, two side choices and a corn bread muffin.","name":"Lil\' Pig (15 Person Minimum)"},{"descriptions":"our award winning, slow smoked chopped pork topped with rich & sassy bbq sauce.","name":"Georgia Chopped Pork Sandwich"},{"descriptions":"(fresh garden or caesar).","name":"Side Salad"},{"descriptions":"grilled salmon fillet basted with a pineapple bbq glaze and served atop a bed of fried onion strings.","name":"Sweet & Sassy Grilled Salmon Platter"},{"descriptions":"(full slab).","name":"Big Baby"},{"descriptions":"melt in your mouth, scratch-made bread pudding and pecan praline sauce served warm with vanilla bean ice cream.","name":"Dave\'s Famous Bread Pudding"},{"descriptions":"served with corn bread muffin and your choice of two sides. (the big slab 12 bones, 1/2 slab 6 bones, 1/3 slab 4 bones).","name":"The Big Slab"},{"descriptions":"varies","name":"Bbq Chicken Wings"},{"descriptions":"dave\'s traditional wings specially seasoned and tossed in your choice of sauce.","name":"Traditional Wings"},{"descriptions":"slow smoked, seasoned with our chicago style rib rub then sauced with sweet & zesty one bite of these babies, and you ve got a mouthful of hollers.","name":"Baby Back Ribs"},{"descriptions":"a classic burger, served with lettuce, tomato and your choice of melted jack or sharp american cheese. without cheese.","name":"Char Grilled Cheeseburger"},{"descriptions":"no longer available for delivery","name":"Kids Meal"},{"descriptions":"your choice of barbeque pulled chicken, texas beef brisket or georgia chopped pork on a bed of crisp greens, smoked bacon, cheddar cheese, diced tomatoes and shoestring potatoes. tossed with our house made honey bbq dressing.","name":"Dave S Sassy Bbq Salad"},{"descriptions":"all the flavor, but half the size of our all american bbq feast. served family-style for 2-3.","name":"Feast For Two"},{"descriptions":"4-bones the bare fact of the matter is dave s ribs are so juicy and tender they don\'t even need sauce to make your mouth water.","name":"Dave S Naked Ribs"},{"descriptions":"a chilled platter of crisp romaine lettuce tossed in our own caesar dressing topped with sliced, grilled chicken breast. without chicken","name":"Grilled Chicken Caesar Salad"},{"descriptions":"no longer available for delivery","name":"Lunch Specials"},{"descriptions":"choose two from below. served with a corn bread muffin. cup of soup or dave s famous chili side salad (fresh garden or caesar) loaded baked Potato with your choice of whipped butter, sour cream, cheddar cheese and bacon pieces.","name":"Soup Salad and Potato Specials"},{"descriptions":"dave\'s original sauce with a blend of hand-picked herbs and spices. heat level - mild.","name":"Rich & Sassy"},{"descriptions":"marinated chicken breast, grilled and topped with jack cheese and two strips of smoked bacon.","name":"Hickory Chicken Sandwich"},{"descriptions":"warm apples sauced in cinnamon and amaretto.","name":"Drunkin Apples"},{"descriptions":"eight strips lightly breaded with cajun seasonings, served with two flavorful sauces: our sweet soul jalapeno and remoulade.","name":"Sweetwater Catfish Fingers"},{"descriptions":"you get: 60 chicken wings, 4 slabs of st. louis style spareribs, 5 pounds of georgia chopped pork, 18 buns and 4 quart size sides.","name":"Bbq Blowout (serves 18)"},{"descriptions":"Dave\'s version includes wilbur beans, famous chili, jalapenos, rich & sassy and your choice of Texas beef brisket, georgia chopped pork or barbeque pulled chicken. nachos grande. nachos for two.","name":"Not\'cho Ordinary Nachos"},{"descriptions":"crispy fried, thick cut, skin on russet potato wedges.","name":"Famous Fries"},{"descriptions":"marinated chicken breast with crisp lettuce and tomato.","name":"Char Grilled Chicken Sandwich"},{"descriptions":"sticky, rich georgia pecan pie, served warm with vanilla bean ice cream and whipped cream.","name":"Better Than Mom\'s Pecan Pie"},{"descriptions":"green beans with bacon, onion, garlic and crushed red pepper.","name":"Firecracker Green Beans"},{"descriptions":"classic southern favorite with jalapeno and chili roasted corn. served with clover honey for the perfect sweet heat combination.","name":"Chili-roasted Corn Fritters"},{"descriptions":"simply seasoned to bring out its natural flavor and tenderness.","name":"Fresh Steamed Broccoli"},{"descriptions":"served with dave\'s own dressing. with grilled chicken breast (chilled & sliced).","name":"Jumbo Caesar Salad"},{"descriptions":"red skin potatoes mixed with milk, butter and garlic.","name":"Garlic Red Skin Mashed Potatoes"},{"descriptions":"don\'t just stick to your ribs, add to them get a 1/3 slab of our award-winning spareribs plus your choice of any one meat selection.","name":"St. Louis Rib-n Meat Bbq Combo"},{"descriptions":"baked beans loaded with smoked pork, brisket, hot link sausage and jalapeno peppers.","name":"Wilbur Beans"},{"descriptions":"choose one meat from below choose two different meats from belo st. louis style spareribs, georgia chopped pork, texas beef brisket, hot link sausage, country roasted or barbeque chicken, traditional or boneless chicken wings, chicken tenders, southside rib tips, beer battered cod, smoked sirloin tri-tip combos and platters served with corn bread muffin and your choice of one side.","name":"Platter and Combo Specials"},{"descriptions":"lip smacking\' 1/2 slab of baby backs and your choice of any one meat selection.","name":"Baby Back N Meat Bbq Combo"},{"descriptions":"warm, walnut covered chocolate brownie soaked with kahlua liqueur and topped with vanilla bean ice cream, hot fudge and whipped cream.","name":"Hot Fudge Kahlua Brownie"},{"descriptions":"flavor permeates the meat, then it\'s flame kissed & crisped.","name":"Bbq Chicken"},{"descriptions":"varies","name":"Dave\'s Famous Chili"},{"descriptions":"buttery, super sweet cobettes.","name":"Corn On The Cob"},{"descriptions":"bbq sandwich choice of georgia chopped pork, texas beef brisket or bbq pulled chicken on a bun plus 2 side choices.","name":"Piglet (15 Person Minimum)"},{"descriptions":"dave\'s fresh made chips loaded with jalapeno bacon and diced tomatoes, topped with tangy bleu cheese dressing and crumbles.","name":"Loaded Bbq Chips"},{"descriptions":"vanilla bean ice cream drizzled with hot fudge or pecan praline sauce and topped with whipped cream.","name":"Famous Sundae"},{"descriptions":"with side salad (fresh garden or caesar).","name":"Cup of Soup"},{"descriptions":"garden greens topped with fried chicken tenders, crisp bacon, grated cheddar, tomatoes and shoestring potatoes tossed with our house made honey bbq dressing.","name":"Crispy Chicken Salad"},{"descriptions":"no bones about it these bbq wings are amazingly meaty all the way through. tossed in your choice of sauce.","name":"Dav\'s Amazingly Boneless Wings"},{"descriptions":"your choice of any of these tender, tasty meats, including beef brisket, chopped pork, bbq or roasted chicken, rib tips, hot link sausage, chicken tenders or wings.","name":"Two-meat Combo"},{"descriptions":"tender to the bone spareribs and your choice of an additional meat.","name":"Rib-n-meat Combo"},{"descriptions":"double your pleasure with any two different meat selections.","name":"Two Meat Bbq Combo"},{"descriptions":"save room for one of dave\'s after dinner minis. choose famous bread pudding, kahlua brownie or strawberry shortcake, each served with vanilla bean ice cream and whipped cream.","name":"Sweet Dixie Minis"},{"descriptions":"texas beef brisket, georgia chopped pork, southside rib tips barbeque or country roasted chicken, chicken tenders, hot link sausage traditional or boneless wings, smoked sirloin tri tip.","name":"Meat Selections"},{"descriptions":"varies","name":"Corn Bread Muffins"},{"descriptions":"crisp, golden-brown chicken tenders tossed in dave\'s special seasoning and served with our own honey bbq sauce.","name":"Chicken Tenders"},{"descriptions":"melted jack cheese, two strips of smoked bacon and dave s favorite sauce rich & sassy atop a char grilled burger.","name":"Dave\'s Favorite Burger"},{"descriptions":"varies","name":"Large Rib 1/2 Slab-6 Bone"},{"descriptions":"our own hickory-smoked salmon, cream cheese, capers and chipotle peppers makes this a spread worth swimming upstream for. served with fire grilled flatbread.","name":"Smoked Salmon Spread"},{"descriptions":"varies","name":"Regular Rib 1/3 Slab-4 Bone"},{"descriptions":"our classic texas beef brisket is rubbed with brown sugar, coarse black pepper and dave\'s secret spices, then slow smoked over hickory until it\'s juicy and tender.","name":"Texas Beef Brisket"},{"descriptions":"varies","name":"Famous Bread Pudding-catering Menu"},{"descriptions":"varies","name":"Slaw or Potato Salad"},{"descriptions":"a meaty burger that\'s really lean now you\'re talkin\' turkey premium ground turkey on a toasted bun loaded with lettuce, tomato, red onion and our special bbq mayo.","name":"Dave\'s Turkey Burger"},{"descriptions":"barbeque ribs, chicken wings, chicken tenders, catfish fingers, and onion strings","name":"Sampler Platter"},{"descriptions":"varies","name":"Fudge Kahlua Brownie-catering Menu"},{"descriptions":"lightly breaded and flash fried, served with new orleans-style remoulade sauce.","name":"Onion Strings"},{"descriptions":"our homestyle version blended with four cheeses, corn and a jalapeno kick.","name":"Dave\'s Cheesy Mac & Cheese"},{"descriptions":"smaller versions of our entree salads served with a corn bread muffin. dave s sassy bbq salad, crispy chicken salad, grilled chicken caesar salad.","name":"Lunch Size Salads"}]'

In [9]:
df['cuisines']

0                                                      NaN
1                                Vegetarian,  Delicatessen
2                                                      NaN
3        Coffee & Tea, Restaurants, American,  Bar,  Pu...
4        Take Out Restaurants, Asian Restaurants, Resta...
                               ...
18150                                                  NaN
18151                               American, ��Vegetarian
18152                                                  NaN
18153    ["Mediterranean","Restaurants","Family Style",...
18154                                                  NaN
Name: cuisines, Length: 18155, dtype: object

In [10]:
df

,address,categories,city,claimed,country,cuisines,dateOpened,dateUpdated,descriptions,facebookPageURL,...,menuURL,name,paymentTypes,phones,postalCode,priceRange,province,sic,twitter,websites
0,2871 Gulf To Bay Blvd,"American, American (new), Clearwater Restauran...",Clearwater,NaN,US,NaN,NaN,2014-02-01T04:41:06Z,"Tags: American (New), American, and Trendy Sta...",NaN,...,NaN,Village Inn Restaurant and Bakery,NaN,7277964988,33759,NaN,FL,8423,NaN,NaN
1,605 W Main St,Caf and Sandwich Place,Louisville,NaN,US,"Vegetarian, Delicatessen",NaN,2016-07-23T22:37:24Z,"Atlantic No. 5, Louisville: See 4 unbiased rev...",NaN,...,NaN,Atlantic No. 5,Yes,5028833398,40202,USD 25.00-40.00,KY,NaN,NaN,atlanticno5.com
2,3803 9th St S W,"American, Barbecue, Puyallup Restaurants, Barb...",Puyallup,NaN,US,NaN,NaN,2015-11-19T22:22:31Z,"Description: Famous Dave's is a Barbecue , Am...",NaN,...,NaN,Famous Dave's,NaN,2536040340,98373,USD 10.00 - USD 15.00,WA,5610,NaN,http://famousdaves.com
3,30 S Main St,"Coffee & Tea, Restaurant, Restaurants, Bar, Am...",Oberlin,NaN,US,"Coffee & Tea, Restaurants, American, Bar, Pu...",NaN,2016-06-20T17:47:10Z,"The Feve, Oberlin: See 170 unbiased reviews of...",NaN,...,/oberlin-oh/mip/the-feve-8940755/menu,The Feve,"mastercard, amex, discover, Yes, visa","[""4407741978"",""4197741978"",""4407753064""]",44074,USD 25.00-40.00,OH,NaN,NaN,http://www.thefeve.com
4,55 Crescent Dr,Sandwich Place and Fast Food Restaurant,Pleasant Hill,yellowpages.com,US,"Take Out Restaurants, Asian Restaurants, Resta...",NaN,2016-07-23T23:55:05Z,"[""https://www.zagat.com/r/yalla-mediterranean-...",NaN,...,/pleasant-hill-ca/mip/yalla-mediterranean-5061...,Quiznos,"master card, visa",9258258644,94523,$,CA,NaN,quiznos,http://www.yallamedi.com/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18150,879 Smith Ave S,"West St Paul Restaurants, American / Diner / C...",W St Paul,NaN,US,NaN,NaN,2013-09-16T03:41:32Z,"Tags: American, Diner, and Coffeehouse",NaN,...,NaN,The Old Man River Cafe,NaN,6.51E+09,55118,NaN,MN,5610,NaN,NaN
18151,1410 Colonial Life Blvd W,Restaurant,Columbia,NaN,US,"American, ��Vegetarian",NaN,2016-04-10T04:24:17Z,"The Melting Pot, Columbia: See 54 unbiased rev...",NaN,...,NaN,The Melting Pot,NaN,8037318500,29210-7665,NaN,SC,NaN,NaN,NaN
18152,9439 Sheridan St,"American, Smoothies & Juices, Hollywood Restau...",Hollywood,NaN,US,NaN,NaN,2013-10-03T01:41:37Z,"Tags: Smoothies & Juice, Vegetarian, and Conve...",NaN,...,NaN,Smoothie King,NaN,9544313411,33024,NaN,FL,0,NaN,http://smoothieking.com
18153,801 N Congress Ave,"[""Restaurants"",""Banquet Halls & Reception Faci...",Boynton Beach,yellowpages.com,US,"[""Mediterranean"",""Restaurants"",""Family Style"",...",NaN,2016-05-31T13:37:09Z,Buca di Beppo serves authentic Italian cuisine...,NaN,...,/boynton-beach-fl/mip/buca-di-beppo-475592729/...,Buca Di Beppo,"amex, cash, discover, all major credit cards, ...","[""5617344558"",""5617330189""]","[""33426""]",$$,FL,5610,NaN,http://www.bucadibeppo.com
18154,1603 Delaware 1,"Rehoboth Beach Restaurants, Pizza / American /...",Rehoboth Beach,NaN,US,NaN,NaN,2013-09-16T04:18:30Z,"Tags: Pizza, American, and Family Style",NaN,...,NaN,Grotto Pizza,NaN,3022273407,19971,NaN,DE,5610,NaN,NaN

In [7]:
df.isna().sum()

address              954
categories           162
city                 621
claimed            17335
country                0
cuisines            7687
dateOpened         17891
dateUpdated            0
descriptions        6931
facebookPageURL    16973
features           11274
hours              10182
images             11579
isClosed           17550
key                    0
lat                 4451
languages          18147
long                4395
menus              11064
menuURL            14699
name                 822
paymentTypes       11905
phones              1714
postalCode           546
priceRange         10408
province             532
sic                10138
twitter            15262
websites            9773
dtype: int64

In [8]:
df['lat'].nunique()

10761

In [9]:
df['long'].nunique()

10814

In [10]:
df_borough = df[['city','lat','long']]

In [12]:
df_borough.shape

(18155, 3)

In [13]:
df_borough.dropna(inplace=True)

<ipython-input-13-b65ebdbe2bb6>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_borough.dropna(inplace=True)

In [14]:
df_borough.shape

(13669, 3)

In [16]:
df_borough['lat'].nunique()

10734

In [17]:
df_borough['long'].nunique()

10742

In [19]:
df_borough.to_csv('../project_data/borough_analysis.csv',index=False)

In [21]:
df['province'].nunique()

52

In [22]:
us_state_abbrev = {
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming',
}

In [23]:
df_province = df.groupby(by='province').agg({'name':'nunique'})

In [25]:
df_province.reset_index(inplace=True)

In [26]:
def func(x, us_):
    return us_[x].lower()

In [29]:
df_province.rename(columns={'province':'region','name':'value'},inplace=True)

In [35]:
df_province

   region  value
0      AK     27
1      AL     81
2      AR     53
4      AZ    194
5      CA   1536
6      CO    281
7      CT    114
9      DE     32
10     FL    660
11     GA    287
12     HI    119
13     IA     75
14     ID     39
15     IL    398
16     IN    153
17     KS     42
18     KY     87
19     LA     93
20     MA    313
21     MD    231
22     ME     99
23     MI    285
24     MN    155
25     MO    169
26     MS     42
27     MT     27
28     NC    261
29     ND     18
30     NE     48
31     NH     62
32     NJ    289
33     NM    125
34     NV    101
35     NY   1008
36     OH    378
37     OK     74
38     OR    303
39     PA    459
40     RI     33
41     SC    108
42     SD     20
43     TN    167
44     TX    635
45     UT    119
46     VA    232
47     VT     51
48     WA    346
49     WI    155
50     WV     50
51     WY     22

In [32]:
df_province = df_province[df_province['region']!="AU-WA"]

In [34]:
df_province = df_province[df_province['region']!="DC"]

In [36]:
df_province['region'] = df_province['region'].apply(lambda x: func(x,us_state_abbrev))

<ipython-input-36-d8f45ee3c765>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_province['region'] = df_province['region'].apply(lambda x: func(x,us_state_abbrev))

In [37]:
df_province

            region  value
0           alaska     27
1          alabama     81
2         arkansas     53
4          arizona    194
5       california   1536
6         colorado    281
7      connecticut    114
9         delaware     32
10         florida    660
11         georgia    287
12          hawaii    119
13            iowa     75
14           idaho     39
15        illinois    398
16         indiana    153
17          kansas     42
18        kentucky     87
19       louisiana     93
20   massachusetts    313
21        maryland    231
22           maine     99
23        michigan    285
24       minnesota    155
25        missouri    169
26     mississippi     42
27         montana     27
28  north carolina    261
29    north dakota     18
30        nebraska     48
31   new hampshire     62
32      new jersey    289
33      new mexico    125
34          nevada    101
35        new york   1008
36            ohio    378
37        oklahoma     74
38          oregon    303
39    pennsylvania    459
40    rhode island     33
41  south carolina    108
42    south dakota     20
43       tennessee    167
44           texas    635
45            utah    119
46        virginia    232
47         vermont     51
48      washington    346
49       wisconsin    155
50   west virginia     50
51         wyoming     22

In [39]:
df_province.to_csv('../project_data/states_grouped_1.csv',index=False)